app/src/main/java/me/banes/chris/tivi/home/HomeActivity.kt, app/src/main/java/me/banes/chris/tivi/home/HomeBuilder.kt, app/src/main/java/me/banes/chris/tivi/home/discover/DiscoverBuilder.kt, app/src/main/java/me/banes/chris/tivi/home/popular/PopularBuilder.kt, app/src/main/java/me/banes/chris/tivi/home/popular/PopularShowsFragment.kt, app/src/main/java/me/banes/chris/tivi/home/trending/TrendingBuilder.kt, app/src/main/java/me/banes/chris/tivi/inject/AppComponent.kt, app/src/main/java/me/banes/chris/tivi/inject/ViewModelBuilder.kt
Did some refactoring because a few classes had a different package name than their parent directory structure.
=> Fix package names of 5 classes

.idea/misc.xml, app/build.gradle, app/schemas/me.banes.chris.tivi.data.TiviDatabase/2.json, app/src/main/java/me/banes/chris/tivi/data/PopularEntry.kt, app/src/main/java/me/banes/chris/tivi/data/TiviShow.kt, app/src/main/java/me/banes/chris/tivi/data/TiviShowDao.kt, app/src/main/java/me/banes/chris/tivi/data/TraktUser.kt, app/src/main/java/me/banes/chris/tivi/data/TrendingEntry.kt
Had to make a few changes to Room entities, but all
good.
=> Move to kapt3

app/build.gradle, app/src/main/java/me/banes/chris/tivi/TiviApplication.kt, build.gradle
Using 1.5.1 due to https://github.com/square/leakcanary/issues/81
=> Integrate LeakCanary

app/src/main/java/me/banes/chris/tivi/home/discover/DiscoverFragment.kt, app/src/main/java/me/banes/chris/tivi/home/library/LibraryFragment.kt, app/src/main/java/me/banes/chris/tivi/util/EntryGridFragment.kt
=> Move VM creation to onCreate

gradle.properties
=> Enable D8 dex compiler

app/build.gradle, base/build.gradle, build.gradle, data/build.gradle
=> Update Arch Components to 1.0.0

app/build.gradle, build.gradle
=> Dependency updates

app/src/main/java/me/banes/chris/tivi/details/ShowDetailsFragment.kt, app/src/main/java/me/banes/chris/tivi/ui/databinding/TiviBindingAdapters.kt, app/src/main/res/layout/view_holder_details_badge.xml, app/src/main/res/layout/view_holder_details_title.xml, app/src/main/res/values/strings.xml, tmdb/src/main/java/me/banes/chris/tivi/tmdb/TmdbImageUrlProvider.kt
:x: This PR branches from #107 (else I got crashes on start) so that needs merging first/this needs cherry-picking of last two commits
Genres before | after
--- | ---
Rating before | after
--- | ---
Network before | after
--- | ---
Certificate before | after
--- | ---
Runtime before | after | after (1 min)
--- | --- | ---
The highlighting of the summary is done automatically by TalkBack on certain API levels to indicate a keyboard focused item (I pressed keyboard taking it out of touch mode). With TalkBack turned off:
=> Add content descriptions for genre and badges in ShowDetails

build.gradle
The newline at the end wasn't me – GitHub added it automatically.
=> Actually update ktlint to 0.19.0

app/src/main/java/me/banes/chris/tivi/actions/TiviActionsImpl.kt, app/src/main/java/me/banes/chris/tivi/home/HomeActivityViewModel.kt, app/src/main/java/me/banes/chris/tivi/inject/AppModule.kt, app/src/main/java/me/banes/chris/tivi/jobs/JobsCreator.kt, app/src/main/java/me/banes/chris/tivi/jobs/TiviJobCreator.kt, app/src/main/java/me/banes/chris/tivi/jobs/UpdateShowFromTMDb.kt, base/src/main/java/me/banes/chris/tivi/actions/TiviActions.kt, trakt/src/main/java/me/banes/chris/tivi/trakt/TraktShowFetcher.kt
Removes the hacky database trigger listener we had in HomeActivityViewModel.
=> Move TMDb update to a Job

app/sampledata/shows.txt, app/src/main/res/layout/fragment_show_details.xml, app/src/main/res/layout/fragment_summary.xml, app/src/main/res/layout/view_holder_details_badge.xml, app/src/main/res/layout/view_holder_details_summary.xml, app/src/main/res/layout/view_holder_details_title.xml, app/src/main/res/layout/view_holder_header.xml, app/src/main/res/layout/view_holder_poster_grid_item.xml
...and also use more fitting sample icons/graphics
=> Use sample show names in layout preview

.circleci/config.yml, ftl-tests/download-results.sh, ftl-tests/run-tests.sh
This will allow us to do multiple runs (different APKs) at the same time
=> Improve FTL test runner to use specified results dir

app/src/main/java/app/tivi/showdetails/details/ShowDetailsEpoxyController.kt, data/build.gradle, data/src/main/java/app/tivi/data/entities/Episode.kt, data/src/main/java/app/tivi/data/entities/EpisodeWatchEntry.kt, data/src/main/java/app/tivi/data/entities/Season.kt, data/src/main/java/app/tivi/data/entities/TiviShow.kt, gradle/config-kotlin-sources.gradle, tmdb-episode-fetcher/src/main/java/app/tivi/tmdb/TmdbEpisodeFetcher.kt, tmdb-show-fetcher/src/main/java/app/tivi/tmdb/TmdbShowFetcher.kt, trakt-episode-fetcher/src/main/java/app/tivi/trakt/TraktEpisodeFetcher.kt, trakt-seasons-fetcher/src/main/java/app/tivi/trakt/TraktSeasonFetcher.kt, trakt-show-fetcher/src/main/java/app/tivi/trakt/TraktShowFetcher.kt
Allows us to move all entity properties to `val`
=> Move to using copy-dynamic

.circleci/config.yml, app/build.gradle, build.gradle
We do this using CircleCI's scheduled build feature.
Since APK versions have to always increment, we use the CI build number as the version code.
=> Nightly builds

app/src/main/java/app/tivi/extensions/ViewExtensions.kt, app/src/main/java/app/tivi/home/HomeFragment.kt, app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt, app/src/main/java/app/tivi/ui/animations/Animators.kt, app/src/main/java/app/tivi/ui/animations/Property.kt, app/src/main/java/app/tivi/ui/databinding/TiviBindingAdapters.kt, app/src/main/java/app/tivi/ui/glide/GlideExtensions.kt, app/src/main/java/app/tivi/ui/glide/GlideTargets.kt, app/src/main/java/app/tivi/ui/glide/SaturationTransitionFactory.kt, app/src/main/java/app/tivi/ui/glide/TiviGlideModule.kt, app/src/main/java/app/tivi/ui/graphics/TiviColorMatrix.kt
Blatantly stealing code from @nickbutcher for the 'saturate on load' animator. Reimplemented it as a GlideType which makes it easier to use, and in Kotlin.
=> Image loading improvements

app/src/main/java/app/tivi/home/discover/DiscoverEpoxyController.kt, app/src/main/java/app/tivi/home/discover/DiscoverFragment.kt
=> Fix Discover to show grid transition

app/build.gradle, app/src/main/java/app/tivi/showdetails/DetailsViewModelModule.java, app/src/main/java/app/tivi/showdetails/DetailsViewModelModule.kt, app/src/main/java/app/tivi/showdetails/ShowDetailsActivity.kt, app/src/main/java/app/tivi/showdetails/ShowDetailsBuilder.kt, app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt, app/src/main/java/app/tivi/showdetails/episodedetails/EpisodeDetailsViewModel.kt
Currently not quite working due to https://github.com/square/AssistedInject/issues/47
=> Move over to AssistedInject

.circleci/config.yml, app/proguard-rules.pro
Split up the Circle CI workflow so that release build is done at the same time as instrumentation tests
=> Use Proguard optimization

app/build.gradle, app/proguard-rules.pro, app/src/main/java/app/tivi/home/HomeViewModel.kt, app/src/main/java/app/tivi/home/discover/DiscoverViewState.kt, app/src/main/java/app/tivi/home/library/LibraryViewState.kt, gradle.properties
Currently blocked on https://issuetracker.google.com/issues/112386012
=> Move over to R8

app/build.gradle, build.gradle
Need to use a recent version of Jetifier
=> Update to Dagger 2.18

app/src/main/java/app/tivi/TiviFragment.kt, app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt, app/src/main/java/app/tivi/ui/databinding/TiviBindingAdapters.kt, app/src/main/java/app/tivi/ui/glide/TiviGlideModule.kt, app/src/main/java/app/tivi/ui/transitions/ColumnedChangeBounds.kt, app/src/main/java/app/tivi/ui/transitions/StartViewChangeBounds.kt, app/src/main/java/app/tivi/ui/transitions/ViewGroupUtils.kt, app/src/main/java/app/tivi/ui/widget/CheckableFloatingActionButton.kt, app/src/main/java/app/tivi/ui/widget/ObservableImageView.kt, app/src/main/java/app/tivi/util/GridToGridTransitioner.kt, app/src/main/res/layout/fragment_show_details.xml, tmdb/src/main/java/app/tivi/tmdb/TmdbImageUrlProvider.kt
Not perfect but a lot better than before
=> Improve poster image shared element transitions

app/src/main/java/app/tivi/home/discover/DiscoverFragment.kt, app/src/main/java/app/tivi/home/library/LibraryFragment.kt, app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt, app/src/main/java/app/tivi/showdetails/episodedetails/EpisodeDetailsFragment.kt
=> Use viewLifecycleOwner for data binding

app/build.gradle
MotionLayout alpha2 has issues when shipped as a
bundle
=> Push APKs to Play for now

app/proguard-rules.pro
Workaround for https://github.com/airbnb/MvRx/issues/185
=> Add new Proguard rule workaround for MvRx

README.md
=> Update KtLint link

app/src/main/java/app/tivi/ui/databinding/TiviBindingAdapters.kt, data/src/main/java/app/tivi/data/resultentities/EntryWithShow.kt, tmdb/src/main/java/app/tivi/tmdb/TmdbImageSizes.kt, tmdb/src/main/java/app/tivi/tmdb/TmdbImageUrlProvider.kt, tmdb/src/main/java/app/tivi/tmdb/TmdbManager.kt
Multiple things going on here:
- TmdbImageUrlProvider was not a data class, so
didn't implement equals()
- BindingAdapter uses doOnLayout, which is not cleared
if the item changes before the layout pass.
Closes #275
=> Fix image posters randomly loading

base/src/main/java/app/tivi/extensions/RetrofitExtensions.kt
Useful for TMDb rate limited requests
=> Honour Retry-After HTTP response

app/src/main/java/app/tivi/extensions/MotionLayoutExtensions.kt, app/src/main/java/app/tivi/home/HomeActivity.kt, app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/fragment_show_details.xml, app/src/main/res/xml/scene_home_nav.xml, app/src/main/res/xml/scene_show_details.xml, build.gradle, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt
DO NOT MERGE. Currently broken.
=> Update ConstraintLayout and MotionLayout to 2.0.0-beta1

app/src/main/java/app/tivi/TiviApplication.kt, app/src/main/java/app/tivi/home/discover/DiscoverViewModel.kt, app/src/main/java/app/tivi/inject/AppComponent.kt, app/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt, app/src/main/java/app/tivi/showdetails/episodedetails/EpisodeDetailsViewModel.kt, app/src/main/java/app/tivi/ui/widget/TopLeftCutoutBackgroundView.kt, build.gradle, interactors/src/main/java/app/tivi/interactors/Interactor.kt, interactors/src/main/java/app/tivi/interactors/SearchShows.kt
=> Treat Kotlin compile warnings as errors

data-android/schemas/app.tivi.data.TiviRoomDatabase/22.json, data/src/main/java/app/tivi/data/repositories/episodes/SeasonsEpisodesRepository.kt, data/src/main/java/app/tivi/data/repositories/followedshows/FollowedShowsRepository.kt, data/src/main/java/app/tivi/data/repositories/popularshows/PopularShowsRepository.kt, data/src/main/java/app/tivi/data/repositories/relatedshows/RelatedShowsRepository.kt, data/src/main/java/app/tivi/data/repositories/traktusers/TraktUsersRepository.kt, data/src/main/java/app/tivi/data/repositories/trendingshows/TrendingShowsRepository.kt, data/src/main/java/app/tivi/data/repositories/watchedshows/WatchedShowsRepository.kt
It breaks database version changes, since the
data is not refreshed again on upgrade.
=> Don't check responseModified flag

buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, interactors/build.gradle, interactors/src/main/java/app/tivi/interactors/ObservePagedFollowedShows.kt, interactors/src/main/java/app/tivi/interactors/ObservePagedPopularShows.kt, interactors/src/main/java/app/tivi/interactors/ObservePagedTrendingShows.kt, ui-followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt
Works better than LiveData + my hacky toFlow()
=> Revert back to using RxPagedListBuilder

app/build.gradle, app/src/main/java/app/tivi/settings/SettingsFragment.kt, app/src/main/res/xml/preferences.xml, build.gradle, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, common-ui/src/main/res/values/strings.xml
=> Show open source licenses

common-ui/src/main/res/values/strings.xml, data/src/main/java/app/tivi/data/daos/FollowedShowsDao.kt, data/src/main/java/app/tivi/data/repositories/followedshows/FollowedShowsRepository.kt, data/src/main/java/app/tivi/data/repositories/followedshows/FollowedShowsStore.kt, domain/src/main/java/app/tivi/domain/observers/ObserveShowViewStats.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsEpoxyController.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsTextCreator.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsViewState.kt, ui-showdetails/src/main/res/layout/view_holder_details_stats.xml
=> Show viewing stats on show details

ui-followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt, ui-watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
We were no longer starting the trakt auth
observer interactor
=> Fix refreshing in Followed and Watched

data/src/main/java/app/tivi/data/repositories/recommendedshows/RecommendedShowsRepository.kt
Data source does not support it yet
=> Stop infinite paging on recommended shows

data-android/src/test/java/app/tivi/data/repositories/SeasonsEpisodesRepositoryTest.kt
=> Use channel for testing flow emissions

build.gradle, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, data-android/build.gradle, data-android/src/main/java/app/tivi/data/DatabaseModule.kt, data-android/src/main/java/app/tivi/data/TiviRoomDatabase.kt
Thanks to @MatrixDev for https://github.com/MatrixDev/Roomigrant
=> Try out Roomigrant for automatic migrations

app/src/main/java/app/tivi/home/HomeActivity.kt, app/src/main/res/layout/view_holder_search_item_show.xml, common-ui/src/main/java/app/tivi/extensions/ViewExtensions.kt, common-ui/src/main/res/drawable/placeholder_small.xml, domain/src/main/java/app/tivi/domain/Interactor.kt, ui-showdetails/src/main/res/layout/fragment_show_details.xml
We no longer close results when the keyboard is
dismissed
=> UX improvements around searching

common-ui/src/main/java/app/tivi/ui/recyclerview/TiviLinearSmoothScroller.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsEpoxyController.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt
Had to create a new LinearSmoothScroller subclass which
allows customisation of the speed, and snapping behavior.
=> Scroll to seasons when expanded

app/src/main/java/app/tivi/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml, app/src/main/res/navigation/discover_nav_graph.xml, app/src/main/res/navigation/following_nav_graph.xml, app/src/main/res/navigation/search_nav_graph.xml, app/src/main/res/navigation/watched_nav_graph.xml, common-ui/src/main/java/app/tivi/extensions/MultipleBackStackNavigationExtensions.kt
Using the extension functions from https://github.com/android/architecture-components-samples/tree/master/NavigationAdvancedSample by @JoseAlcerreca
=> Add multiple-back stacks to Bottom Navigation

ui-discover/src/main/java/app/tivi/home/discover/DiscoverFragment.kt
Fix issue: https://github.com/chrisbanes/tivi/issues/481
=> Save carousel's scroll position in DisCoverFragment

ui-discover/src/main/java/app/tivi/home/discover/DiscoverFragment.kt
=> Revert "Save carousel's scroll position in DiscoverFragment"

app/build.gradle, app/src/main/java/app/tivi/appinitializers/ArchTaskExecutorInitializer.kt, app/src/main/res/menu/home_bottomnav.xml, app/src/main/res/navigation/search_nav_graph.xml, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, common-epoxy/src/main/java/app/tivi/common/epoxy/SwipeAwayCallbacks.kt, common-ui/src/main/res/values/attrs.xml, common-ui/src/main/res/values/strings.xml, data-android/src/main/java/app/tivi/data/FlowPagedListBuilder.kt, gradle.properties, ui-search/src/main/res/menu/search_toolbar.xml
Required a workaround for ConstraintLayout
=> Update to AGP 3.6.0-alpha12

common-ui/src/main/java/app/tivi/ui/widget/TopLeftCutoutBackgroundView.kt
Way nicer, and more optimal than creating a new shape appearance model each update
=> Use MaterialShapeDrawable.interpolation

.circleci/config.yml, build.gradle, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, gradle.properties
=> CI Build Improvements

ui-showdetails/src/main/res/xml/scene_show_details.xml
It doesn't feel natural, but it gives the correct end result.
Closes #522
=> Force show details to fling to open state

app/src/main/java/app/tivi/inject/AppModuleBinds.kt, app/src/main/java/app/tivi/util/AndroidPowerController.kt, base/src/main/java/app/tivi/util/PowerController.kt, common-imageloading/src/main/java/app/tivi/common/imageloading/TmdbImageEntityCoilMapper.kt
Currently this happens when power saver is enabled, or when data saver is enabled. Eventually this will be a setting too.
=> Fetch lower quality images when needed

common-imageloading/src/main/java/app/tivi/common/imageloading/TmdbImageEntityCoilMapper.kt, common-ui-resources/src/main/res/values/strings.xml
Thanks to @MartelliEnrico for the catch!
=> Tweaks to data-saver

README.md
As not using fabric anymore.
**Reference revision:**
Remove Fabric and move to Firebase client lib
Revision - 1f5f4cf9cc0851335e942efb0279d57c0c6ee770
=> Updated the development setup instructions.

build.gradle, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, common-ui-compose/build.gradle, common-ui-compose/src/main/java/app/tivi/common/compose/ComposeTypedArray.kt, common-ui-compose/src/main/java/app/tivi/common/compose/MaterialThemeFromContext.kt, ui-episodedetails-compose/build.gradle, ui-episodedetails-compose/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt, ui-showdetails-view/build.gradle, ui-showdetails-view/src/main/java/app/tivi/showdetails/details/view/ShowDetails.kt
Had to pin our Kotlin source level to 1.3 since Compose now depends on the 1.4 Kotlin compiler
=> Update to Compose 0.1.0-dev10

README.md
=> Document new oauth redirect URI

app/build.gradle, build.gradle, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, gradle/wrapper/gradle-wrapper.properties
Needed to disable Play publishing due to https://github.com/Triple-T/gradle-play-publisher/issues/813
=> Update to AGP 4.1.0-alpha10 and Gradle 6.5-m1

app/build.gradle, build.gradle
Trying out the fix for https://github.com/Triple-T/gradle-play-publisher/issues/813
=> Try out Play Publisher 2.8.0-SNAPSHOT

buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, common-epoxy/build.gradle, common-layouts/build.gradle, ui-discover/build.gradle, ui-followed/build.gradle, ui-search/build.gradle, ui-watched/build.gradle
Enables incremental annotation processing, and parallel processing. Maor speed!
=> Update to Epoxy 4.0.0-beta4

.github/workflows/build.yml, .github/workflows/release-management.yml, README.md
Updating refs in CI scripts + README
=> Migrate to main branch naming

common-ui-view/src/main/java/app/tivi/ReduxViewModel.kt, data/src/main/java/app/tivi/data/daos/UserDao.kt, domain/src/main/java/app/tivi/domain/observers/ObserveUserDetails.kt, ui-discover/src/main/java/app/tivi/home/discover/DiscoverViewModel.kt, ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewModel.kt, ui-followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt, ui-watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
Users can be null in the database, therefore the user flows should be of a nullable type.
=> Fix crash due to wrong nullability

app/build.gradle, app/fake-google-services.json
This allows devs to play around with the source without creating a Firebase app
Fixes #679
=> Add a fake google-services.json

common-ui-compose/src/main/java/app/tivi/common/compose/LazyList.kt, ui-search/src/main/java/app/tivi/home/search/Search.kt
https://issuetracker.google.com/167913500
=> Add workaround for search items clipping

common-ui-compose/build.gradle, common-ui-compose/src/main/java/app/tivi/common/compose/Elevation.kt, common-ui-compose/src/main/java/app/tivi/common/compose/TiviSetup.kt, ui-account/src/main/java/app/tivi/account/AccountUiFragment.kt, ui-discover/src/main/java/app/tivi/home/discover/Discover.kt, ui-discover/src/main/java/app/tivi/home/discover/DiscoverFragment.kt, ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt, ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsFragment.kt, ui-search/src/main/java/app/tivi/home/search/Search.kt, ui-search/src/main/java/app/tivi/home/search/SearchFragment.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt
This is important for show details, because it uses nested surfaces which are each elevated.
Tracking feature request for Compose: https://issuetracker.google.com/171031040
=> Add implementation of absolute elevation

build.gradle, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, common-ui-compose/src/main/java/app/tivi/common/compose/DeferredIcon.kt, common-ui-compose/src/main/java/app/tivi/common/compose/ExpandingFloatingActionButton.kt, common-ui-compose/src/main/java/app/tivi/common/compose/vector.kt, gradle/wrapper/gradle-wrapper.properties, ui-discover/src/main/java/app/tivi/home/discover/Discover.kt, ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt, ui-search/src/main/java/app/tivi/home/search/Search.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt
Also updated AGP, Gradle and various other deps
=> Update to Compose SNAPSHOT 6922857

.github/workflows/build.yml, app/build.gradle, build.gradle, buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt, gradle/wrapper/gradle-wrapper.properties
Had to disable Play Publishing due to: https://github.com/Triple-T/gradle-play-publisher/issues/889
=> Update to AGP 7.0.0-alpha02

gradle/wrapper/gradle-wrapper.properties, versions.gradle
=> Update to Compose SNAPSHOT 7154166

.github/workflows/build.yml, data/src/main/java/app/tivi/data/repositories/episodes/TraktSeasonsEpisodesDataSource.kt, gradle/wrapper/gradle-wrapper.properties, lint.xml, versions.gradle
Also updated AGP, Gradle, Kotlin and most other dependencies
Had to disable running tests for now due to https://issuetracker.google.com/182468430
=> Update to Compose 1.0.0-beta02

app/src/main/java/app/tivi/home/Home.kt, app/src/main/java/app/tivi/home/MainActivity.kt, common-ui-compose/src/main/java/app/tivi/common/compose/PosterCard.kt, common-ui-compose/src/main/java/app/tivi/common/compose/UserProfileButton.kt, ui-account/src/main/java/app/tivi/account/AccountUi.kt, ui-account/src/main/java/app/tivi/account/AccountUiFragment.kt, ui-discover/src/main/java/app/tivi/home/discover/Discover.kt, ui-discover/src/main/java/app/tivi/home/discover/DiscoverFragment.kt, ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt, ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsFragment.kt, ui-followed/src/main/java/app/tivi/home/followed/Followed.kt, ui-followed/src/main/java/app/tivi/home/followed/FollowedFragment.kt, ui-popular/src/main/java/app/tivi/home/popular/Popular.kt, ui-popular/src/main/java/app/tivi/home/popular/PopularShowsFragment.kt, ui-recommended/src/main/java/app/tivi/home/recommended/Recommended.kt, ui-recommended/src/main/java/app/tivi/home/recommended/RecommendedShowsFragment.kt, ui-search/src/main/java/app/tivi/home/search/Search.kt, ui-search/src/main/java/app/tivi/home/search/SearchFragment.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt, ui-trending/src/main/java/app/tivi/home/trending/Trending.kt, ui-trending/src/main/java/app/tivi/home/trending/TrendingShowsFragment.kt, ui-watched/src/main/java/app/tivi/home/watched/Watched.kt, ui-watched/src/main/java/app/tivi/home/watched/WatchedFragment.kt, versions.gradle
=> Migrate to Google Accompanist

build.gradle, data-android/build.gradle, data-android/src/main/java/app/tivi/data/DatabaseInject.kt, data-android/src/main/java/app/tivi/data/TiviRoomDatabase.kt, gradle/libs.versions.toml
See this [article](https://medium.com/androiddevelopers/room-auto-migrations-d5370b0ca6eb) by @florina-muntenescu for more information.
=> Try out Room auto-migrations

app/proguard-rules.pro, gradle.properties
Using the workaround rules in https://issuetracker.google.com/191654433
=> Re-enable R8 full mode

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
..and lots of other dependencies.
=> Update to Compose 1.0.0-rc01

ui-discover/src/main/java/app/tivi/home/discover/Discover.kt
Implement TODO in Discover.kt.
=> Remove action in Discover.kt

app/src/main/java/app/tivi/AppNavigation.kt
Currently the leaf screens are added multiple times across different 'top-level' nav graphs, but the same route.
This means that navigation doesn't know what destination to choose navigating, and can result in navigate calls crossing nav graphs.
This PR fixes that by making each destination globally unique. For example, instead of adding the route `show/{id}` multiple times, we now add:
- `discover/show/{id}`
- `watched/show/{id}`
- `search/show/{id}`
This is done across all of the leaf screens, by forcing all of the routes to be created with a 'root' screen route.
=> Make navigation destinations unique

app/src/main/java/app/tivi/AppNavigation.kt, app/src/main/java/app/tivi/home/Home.kt, gradle/libs.versions.toml
Very early rough integration, but it works. Hopefully there will be `Scaffold` support at some point.
=> Use a `NavigationRail` on devices with width > 600dp

.idea/inspectionProfiles/ktlint.xml, README.md, app/proguard-rules.pro, gradle/libs.versions.toml
There's no need for us to force Bumblebee on people right now.
=> Revert back to AGP 7.0.4

ui-episodedetails/build.gradle, ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt
Caused by us not using Accompanist Scaffold which automatically sets up the nested content padding for us.
=> Fix Episode Details content being under nav bar

app/build.gradle, app/src/main/java/app/tivi/home/MainActivity.kt, app/src/main/java/app/tivi/inject/AppModule.kt, app/src/main/java/app/tivi/inject/NetworkModule.kt, app/src/qa/kotlin/app/tivi/NetworkBehaviorSimulatorInterceptor.kt, app/src/qa/kotlin/app/tivi/home/QaContentViewModule.kt, app/src/qa/kotlin/app/tivi/inject/QaNetworkModule.kt, app/src/standard/kotlin/app/tivi/home/StandardContentViewModule.kt, app/src/standard/kotlin/app/tivi/inject/StandardNetworkModule.kt, common-ui-view/src/main/java/app/tivi/ContentViewSetter.kt, gradle/libs.versions.toml, trakt/src/main/java/app/tivi/trakt/TraktModule.kt
Uses https://github.com/Gridstone/DebugDrawer and most of the provided modules (thanks @chris-horner!)
Includes an OkHttp interceptor which allows simulating of different network behavior (delay, errors, etc) when using the real network endpoint.
=> Add 'debug drawer' to Tivi

app/src/main/java/app/tivi/AppNavigation.kt, app/src/main/java/app/tivi/NavigationUtils.kt, app/src/main/java/app/tivi/home/Home.kt, base-android/src/main/java/app/tivi/util/TiviAnalytics.kt, ui-popular/src/main/java/app/tivi/home/popular/Popular.kt, ui-recommended/src/main/java/app/tivi/home/recommended/Recommended.kt, ui-trending/src/main/java/app/tivi/home/trending/Trending.kt
Thanks to @ianhanniballake for the ideas in https://issuetracker.google.com/issues/211580606
=> Add debug labels to Analytics events

app/build.gradle, base/build.gradle, data/build.gradle, data/src/main/java/app/tivi/data/RetrofitExtensions.kt, data/src/main/java/app/tivi/data/repositories/episodes/TmdbEpisodeDataSource.kt, data/src/main/java/app/tivi/data/repositories/episodes/TraktEpisodeDataSource.kt, data/src/main/java/app/tivi/data/repositories/episodes/TraktSeasonsEpisodesDataSource.kt, data/src/main/java/app/tivi/data/repositories/followedshows/TraktFollowedShowsDataSource.kt, data/src/main/java/app/tivi/data/repositories/popularshows/TraktPopularShowsDataSource.kt, data/src/main/java/app/tivi/data/repositories/recommendedshows/TraktRecommendedShowsDataSource.kt, data/src/main/java/app/tivi/data/repositories/relatedshows/TmdbRelatedShowsDataSource.kt, data/src/main/java/app/tivi/data/repositories/relatedshows/TraktRelatedShowsDataSource.kt, data/src/main/java/app/tivi/data/repositories/search/TmdbSearchDataSource.kt, data/src/main/java/app/tivi/data/repositories/showimages/TmdbShowImagesDataSource.kt, data/src/main/java/app/tivi/data/repositories/shows/TmdbShowDataSource.kt, data/src/main/java/app/tivi/data/repositories/shows/TraktShowDataSource.kt, data/src/main/java/app/tivi/data/repositories/traktusers/TraktUsersDataSource.kt, data/src/main/java/app/tivi/data/repositories/traktusers/TraktUsersRepository.kt, data/src/main/java/app/tivi/data/repositories/trendingshows/TraktTrendingShowsDataSource.kt, data/src/main/java/app/tivi/data/repositories/watchedshows/TraktWatchedShowsDataSource.kt, tmdb/src/main/java/app/tivi/tmdb/TmdbManager.kt
https://dagger.dev/hilt/gradle-setup.html#aggregating-task
Fixes #851
=> Enable Hilt's Aggregating task

common-ui-compose/src/main/java/app/tivi/common/compose/EntryGrid.kt, common-ui-compose/src/main/java/app/tivi/common/compose/LazyList.kt, ui-followed/src/main/java/app/tivi/home/followed/Followed.kt, ui-watched/src/main/java/app/tivi/home/watched/Watched.kt
=> Migrate to LazyVerticalGrid

benchmark/benchmark-rules.pro, benchmark/build.gradle, benchmark/src/main/java/app/tivi/benchmark/BaselineProfileGenerator.kt, gradle/wrapper/gradle-wrapper.properties
Main issue was the missing kotlin gradle plugin.
Also added a baseline profile generator.
=> Fix baseline profile setup

app/src/main/java/app/tivi/appinitializers/EmojiInitializer.kt, app/src/main/java/app/tivi/home/Home.kt, common-ui-compose/src/main/java/app/tivi/common/compose/EntryGrid.kt, common-ui-compose/src/main/java/app/tivi/common/compose/theme/Type.kt, common-ui-compose/src/main/java/app/tivi/common/compose/ui/FilterSortPanel.kt, common-ui-compose/src/main/java/app/tivi/common/compose/ui/PosterCard.kt, common-ui-compose/src/main/java/app/tivi/common/compose/ui/RefreshButton.kt, common-ui-compose/src/main/java/app/tivi/common/compose/ui/SearchTextField.kt, common-ui-compose/src/main/java/app/tivi/common/compose/ui/SortMenuPopup.kt, common-ui-compose/src/main/java/app/tivi/common/compose/ui/UserProfileButton.kt, common-ui-view/src/main/java/app/tivi/ui/GenreStringer.kt, common-ui-view/src/main/java/app/tivi/util/TiviTextCreator.kt, gradle.properties, ui-account/src/main/java/app/tivi/account/AccountUi.kt, ui-discover/src/main/java/app/tivi/home/discover/Discover.kt, ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt, ui-followed/src/main/java/app/tivi/home/followed/Followed.kt, ui-popular/src/main/java/app/tivi/home/popular/Popular.kt, ui-recommended/src/main/java/app/tivi/home/recommended/Recommended.kt, ui-search/src/main/java/app/tivi/home/search/Search.kt, ui-settings/src/main/java/app/tivi/settings/SettingsPreferenceFragment.kt, ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt, ui-showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasons.kt, ui-trending/src/main/java/app/tivi/home/trending/Trending.kt, ui-watched/src/main/java/app/tivi/home/watched/Watched.kt
https://blog.blundellapps.co.uk/speed-up-your-build-non-transitive-r-files/
=> Disable transitive R file generation

.github/workflows/build.yml, .github/workflows/scheduled.yml, settings.gradle
Use [gradle-build-action](https://github.com/gradle/gradle-build-action) to speed up build.
=> Optimize CI a bit

build.gradle, gradle/libs.versions.toml
https://developer.android.com/studio/releases/gradle-plugin#7-3-0
=> Bump AGP to 7.3.0 final

build.gradle.kts, data-android/build.gradle.kts, gradle/libs.versions.toml
This PR would be a part of replacing kapt like #951.
=> Replace room's kapt with ksp

.gitignore, api/tmdb/build.gradle.kts, api/trakt-auth/build.gradle.kts, api/trakt/build.gradle.kts, app/build.gradle.kts, build.gradle.kts, common/imageloading/build.gradle.kts, core/analytics/build.gradle.kts, core/logging/build.gradle.kts, data-android/build.gradle.kts, domain/build.gradle.kts, gradle/libs.versions.toml, tasks/build.gradle.kts, ui/account/build.gradle.kts, ui/discover/build.gradle.kts, ui/episodedetails/build.gradle.kts, ui/followed/build.gradle.kts, ui/popular/build.gradle.kts, ui/recommended/build.gradle.kts, ui/search/build.gradle.kts, ui/settings/build.gradle.kts, ui/showdetails/build.gradle.kts, ui/showseasons/build.gradle.kts, ui/trending/build.gradle.kts, ui/watched/build.gradle.kts
Migrates to @sergei-lapin's [napt](https://github.com/sergei-lapin/napt), to replace kapt.
- Had to disable Hilt's aggregating task as it doesn't seem to work with napt
- gitignore NaptTrigger
=> [WIP] Try out sergei-lapin/napt

.gitignore, gradle/libs.versions.toml
https://github.com/sergei-lapin/napt/releases/tag/1.17
=> Bump Napt to 1.17

app/build.gradle.kts, common/ui/compose/build.gradle.kts, gradle.properties
https://blog.gradle.org/introducing-file-system-watching
=> Speed up builds a bit

gradle.properties
https://developer.android.com/studio/releases/gradle-plugin#experimental_further_app_size_reductions
```
OLD: old_app-qa-release.apk (signature: V1, V2)
NEW: new_app-qa-release.apk (signature: V1, V2)
│             compressed             │            uncompressed
├───────────┬───────────┬────────────┼───────────┬───────────┬────────────
APK      │ old       │ new       │ diff       │ old       │ new       │ diff
──────────┼───────────┼───────────┼────────────┼───────────┼───────────┼────────────
dex │   2.8 MiB │   2.8 MiB │        0 B │   5.8 MiB │   5.8 MiB │        0 B
arsc │ 920.6 KiB │ 750.4 KiB │ -170.3 KiB │ 920.5 KiB │ 750.3 KiB │ -170.3 KiB
manifest │   5.3 KiB │   5.3 KiB │        0 B │  25.4 KiB │  25.4 KiB │        0 B
res │ 496.3 KiB │ 485.7 KiB │  -10.6 KiB │ 620.3 KiB │ …
```
=> Tweak more flags

gradle/libs.versions.toml
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.9
https://github.com/google/dagger/releases/tag/dagger-2.44
=> Robolectric 4.9 & Dagger 2.44

common/ui/compose/build.gradle.kts, gradle/libs.versions.toml
See here for more info: https://android-developers.googleblog.com/2022/10/whats-new-in-jetpack-compose.html
=> Use new Compose BOM: 2022.10.00

.github/workflows/build.yml
https://github.com/gradle/gradle-build-action/releases/tag/v2.3.0
https://github.com/gradle/gradle-build-action/blob/main/README.md#removing-unused-files-from-gradle-user-home-before-saving-to-cache
=> Enable gradle-home-cache-cleanup on gradle-build-action

.idea/kotlinc.xml, common/ui/compose/build.gradle.kts, common/ui/compose/src/main/java/app/tivi/common/compose/EntryGrid.kt, gradle/libs.versions.toml, ui/discover/build.gradle.kts, ui/discover/src/main/java/app/tivi/home/discover/Discover.kt, ui/followed/build.gradle.kts, ui/followed/src/main/java/app/tivi/home/followed/Followed.kt, ui/watched/build.gradle.kts, ui/watched/src/main/java/app/tivi/home/watched/Watched.kt
Follow up #1007.
https://github.com/google/accompanist/releases/tag/v0.27.1
https://google.github.io/accompanist/swiperefresh/#migration
=> Migrate SwipeRefresh to PullRefresh

app/src/main/AndroidManifest.xml, app/src/main/res/xml/backup_rules.xml, app/src/main/res/xml/data_extraction_rules.xml
Currently everything will be backed up, including auth tokens.
Fixes #1031
=> Only backup preferences

api/trakt-auth/build.gradle.kts, api/trakt-auth/src/main/java/app/tivi/trakt/TraktManager.kt, api/trakt-auth/src/main/java/app/tivi/trakt/store/AuthStore.kt, api/trakt-auth/src/main/java/app/tivi/trakt/store/BlockStoreAuthStore.kt, api/trakt-auth/src/main/java/app/tivi/trakt/store/PreferencesAuthStore.kt, gradle/libs.versions.toml
https://developers.google.com/identity/blockstore/android
=> Integrate Block Store

build.gradle.kts, gradle/libs.versions.toml, ui/showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsViewModel.kt
Spotless supports editorconfig by default now.
https://github.com/diffplug/spotless/blob/main/CHANGES.md#2320---2023-01-13 https://github.com/pinterest/ktlint/releases/tag/0.48.1
=> Spotless 6.13.0 & Ktlint 0.48.1

common/ui/compose/src/main/java/app/tivi/common/compose/ui/AppBar.kt, gradle/libs.versions.toml, ui/account/build.gradle.kts, ui/account/src/main/java/app/tivi/account/AccountUi.kt, ui/discover/build.gradle.kts, ui/discover/src/main/java/app/tivi/home/discover/Discover.kt, ui/episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt, ui/library/build.gradle.kts, ui/showdetails/build.gradle.kts, ui/showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt, ui/showseasons/build.gradle.kts, ui/showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasons.kt, ui/upnext/build.gradle.kts
Using the new alpha [Compose BOM](https://github.com/chrisbanes/compose-bom).
=> Update to Jetpack Compose 1.4.0-x

.github/workflows/baseline-profile.yml, app/src/main/java/app/tivi/home/Home.kt, benchmark/src/main/java/app/tivi/benchmark/BaselineProfileGenerator.kt, gradle/libs.versions.toml, ui/discover/build.gradle.kts, ui/discover/src/main/java/app/tivi/home/discover/Discover.kt, ui/episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt, ui/showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt, ui/showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasons.kt
- The baseline profile generation test now attempts to flow through the app a bit more, to deliver more accurate baseline profiles.
- Use ReportDrawnWhen on ui-discover
=> Realistic flow for baseline profile generation

app/build.gradle.kts, app/src/main/java/app/tivi/inject/AppModule.kt, core/analytics/build.gradle.kts, core/analytics/src/main/java/app/tivi/util/AnalyticsModule.kt, core/analytics/src/main/java/app/tivi/util/TiviFirebaseAnalytics.kt, core/logging/build.gradle.kts, core/logging/src/main/AndroidManifest.xml, core/logging/src/main/java/app/tivi/util/TiviLogger.kt, gradle/libs.versions.toml
Also tidied up how Firebase classes show up in the DI graph.
=> Use Firebase's BOM to manage versions

.github/workflows/baseline-profile.yml, app/src/main/java/app/tivi/appinitializers/TimberInitializer.kt, benchmark/src/main/java/app/tivi/benchmark/BaselineProfileGenerator.kt, ui/showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt
Caused by a few issues:
- The emulator profile used didn't allow internet access (not sure why)
- We now wait up to 5 seconds for objects to appear because proceeding.
- Simplified the 'show details' scenario
=> Deflake baseline profile generation

app/src/main/java/app/tivi/AppNavigation.kt, ui/episodedetails/build.gradle.kts, ui/episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt
=> [Episode Details] Modal sheet improvements

gradle.properties, settings.gradle.kts
- [Reduce max heap size to 3GB](https://github.com/chrisbanes/tivi/commit/72400f97696bbad9712137ca57c83dcbdab2f10d)
- [Re-enable configuration caching](https://github.com/chrisbanes/tivi/commit/4d3f7f77de1ca0b0c705c4196708766135a8932b)
=> Gradle setup tweaks

data-android/build.gradle.kts, data-android/src/main/java/app/tivi/data/StoreExtensions.kt, data-android/src/main/java/app/tivi/data/repositories/popularshows/PopularShowsModule.kt, data-android/src/main/java/app/tivi/data/repositories/recommendedshows/RecommendedShowsModule.kt, data-android/src/main/java/app/tivi/data/repositories/relatedshows/RelatedShowsModule.kt, data-android/src/main/java/app/tivi/data/repositories/showimages/ShowsImagesModule.kt, data-android/src/main/java/app/tivi/data/repositories/shows/ShowsModule.kt, data-android/src/main/java/app/tivi/data/repositories/trendingshows/TrendingShowsModule.kt, data-android/src/main/java/app/tivi/data/repositories/watchedshows/WatchedShowsModule.kt, data/build.gradle.kts, domain/src/main/java/app/tivi/domain/observers/ObserveShowDetails.kt, domain/src/main/java/app/tivi/domain/observers/ObserveShowImages.kt, gradle/libs.versions.toml
See https://mobilenativefoundation.github.io/Store/
Had to add atomicfu as a dependency too
=> Migrate to Store5

api/tmdb/build.gradle.kts, api/tmdb/src/main/java/app/tivi/tmdb/TmdbManager.kt, app/proguard-rules.pro, data/legacy/src/main/java/app/tivi/data/mappers/TmdbShowDetailToShowImages.kt, data/legacy/src/main/java/app/tivi/data/mappers/TmdbShowDetailToTiviShow.kt, data/relatedshows/src/main/java/app/tivi/data/relatedshows/RelatedShowsBinds.kt, data/relatedshows/src/main/java/app/tivi/data/relatedshows/TmdbRelatedShowsDataSourceImpl.kt, data/showimages/src/main/java/app/tivi/data/showimages/TmdbShowImagesDataSource.kt, gradle/libs.versions.toml
Complete the missing TMDB endpoints from the library MoviebaseApp/tmdb-api.
=> Complete @MoviebaseApp/tmdb-api

api/tmdb/src/main/java/app/tivi/tmdb/TmdbComponent.kt, data/test/src/test/java/app/tivi/data/DatabaseTest.kt, gradle/libs.versions.toml
- Update the library for using HttpClient configuration
- Fix unit tests
=> Update tmdb-api to 0.9.0

api/trakt-auth/android/src/main/java/app/tivi/trakt/store/BlockStoreAuthStore.kt
This reverts commit eb397278c2f0b8d6c3fc1138b91c6d8a1b5a014a.
=> Revert "Update BlockStoreAuthStore to new APIs"

api/tmdb/src/commonMain/kotlin/app/tivi/tmdb/TmdbManager.kt
Fix crash when TMDB configuration request fails somehow (timeout, http error, no internet, etc.)
=> Fix crash for failing TMDB configuration request

gradle.properties
Follow up #1200.
https://developer.android.com/build/releases/gradle-plugin#default-changes
=> Remove default flags

core/logging/build.gradle.kts, core/logging/src/androidMain/kotlin/app/tivi/util/TiviLogger.kt, core/logging/src/commonMain/kotlin/app/tivi/util/KermitLogger.kt, core/logging/src/commonMain/kotlin/app/tivi/util/LoggerComponent.kt, core/logging/src/jvmMain/kotlin/app/tivi/util/LoggerComponent.kt, gradle/libs.versions.toml
I might migrate over from Timber for the Android platform too, but the automatic tagging is nice.
=> Add Kermit logger for JVM

app/build.gradle.kts, app/src/main/java/app/tivi/inject/ApplicationComponent.kt, core/performance/build.gradle.kts, core/performance/src/androidMain/kotlin/app/tivi/core/perf/AndroidTracer.kt, core/performance/src/androidMain/kotlin/app/tivi/core/perf/PerformanceComponent.kt, core/performance/src/commonMain/kotlin/app/tivi/core/perf/Tracer.kt, gradle/libs.versions.toml, settings.gradle.kts
Need to start tracking app startup time as it's gotten a little slow lately.
=> Add Firebase Performance monitoring

data/episodes/src/commonMain/kotlin/app/tivi/data/episodes/TmdbEpisodeDataSourceImpl.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/ShowIdToTmdbIdMapper.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/traktauth/RelatedShowsStore.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/traktauth/TmdbRelatedShowsDataSourceImpl.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/traktauth/TraktRelatedShowsDataSourceImpl.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateRelatedShows.kt
Stopped sending exceptions to the logger too. They're pretty useless.
=> Use both Trakt/TMDb for related shows

data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/EpisodeIdToTraktIdMapper.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/Mapper.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/Mappers.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/SeasonIdToTraktIdMapper.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/ShowIdToTmdbIdMapper.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/ShowIdToTraktIdMapper.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TmdbEpisodeDetailToEpisode.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TmdbShowDetailToShowImages.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TmdbShowDetailToTiviShow.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TmdbShowPageResultToTiviShows.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TmdbShowToTiviShow.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktBaseShowToWatchedShowEntry.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktEpisodeToEpisode.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktHistoryEntryToEpisode.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktHistoryItemToEpisodeWatchEntry.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktListItemToFollowedShowEntry.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktListItemToTiviShow.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktSeasonToSeason.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktSeasonToSeasonWithEpisodes.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktShowToTiviShow.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktStatusToShowStatus.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktTrendingShowToTiviShow.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/TraktTrendingShowToTrendingShowEntry.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/UserToTraktUser.kt
As all of the DB layer is now blocking, there's no reason for the model mappers to be suspending.
=> Make model mappers blocking

data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/daos/SqlDelightFollowedShowsDao.kt, data/db-sqldelight/src/commonMain/sqldelight/migrations/29.sqm, data/db-sqldelight/src/commonMain/sqldelight/migrations/30.sqm, data/db-sqldelight/src/commonMain/sqldelight/migrations/31.sqm, data/episodes/src/commonMain/kotlin/app/tivi/data/episodes/EpisodeWatchStore.kt, data/followedshows/src/commonMain/kotlin/app/tivi/data/followedshows/FollowedShowsRepository.kt
Small issues which have popped up in Crashlytics
=> A few database fixes

.github/workflows/baseline-profile.yml, .github/workflows/build.yml
See: https://github.com/gradle/wrapper-validation-action
=> Validate Gradle Wrapper

ui/library/src/main/java/app/tivi/home/library/LibraryViewModel.kt, ui/upnext/src/main/java/app/tivi/home/upnext/UpNextViewModel.kt
=> Tidy up preferences collection in composables

android-app/app/src/main/java/app/tivi/home/MainActivityViewModel.kt, data/episodes/src/commonMain/kotlin/app/tivi/data/episodes/SeasonsEpisodesRepository.kt, data/followedshows/src/commonMain/kotlin/app/tivi/data/followedshows/FollowedShowsRepository.kt, domain/src/commonMain/kotlin/app/tivi/domain/PaginatedEntryRemoteMediator.kt, domain/src/commonMain/kotlin/app/tivi/domain/RefreshOnlyRemoteMediator.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateLibraryShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateRecommendedShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateRelatedShows.kt
We need to re-throw them but there's a handful of places where we don't do that.
=> Stop catching CancellationExceptions

android-app/app/src/main/java/app/tivi/inject/DataComponent.kt, common/imageloading/src/main/java/app/tivi/common/imageloading/ShowCoilInterceptor.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/lastrequests/EntityLastRequestStore.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/lastrequests/GroupLastRequestStore.kt, data/legacy/src/commonMain/kotlin/app/tivi/data/util/StoreExtensions.kt, data/models/src/commonMain/kotlin/app/tivi/data/models/ShowImages.kt, data/popularshows/src/commonMain/kotlin/app/tivi/data/popularshows/PopularShowsStore.kt, data/recommendedshows/src/commonMain/kotlin/app/tivi/data/recommendedshows/RecommendedShowsStore.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/relatedshows/RelatedShowsBinds.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/relatedshows/RelatedShowsDataSource.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/relatedshows/RelatedShowsLastRequestStore.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/relatedshows/RelatedShowsStore.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/relatedshows/TmdbRelatedShowsDataSourceImpl.kt, data/relatedshows/src/commonMain/kotlin/app/tivi/data/relatedshows/TraktRelatedShowsDataSourceImpl.kt, data/showimages/src/commonMain/kotlin/app/tivi/data/showimages/ShowImagesStore.kt, data/shows/src/commonMain/kotlin/app/tivi/data/shows/ShowStore.kt, data/trendingshows/src/commonMain/kotlin/app/tivi/data/trendingshows/TrendingShowsStore.kt, data/watchedshows/src/commonMain/kotlin/app/tivi/data/watchedshows/WatchedShowsStore.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateRelatedShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/observers/ObserveShowDetails.kt, domain/src/commonMain/kotlin/app/tivi/domain/observers/ObserveShowImages.kt, gradle/libs.versions.toml
=> Update to store5 to 5.0.0-beta01

.github/workflows/build.yml, .github/workflows/publish-ios.yml, ios-app/Tivi/fastlane/Fastfile, ios-app/Tivi/fastlane/README.md
We use Fastlane to build the iOS app via Xcode. Also migrated to use the App Store Connect API
=> Build iOS app on CI

settings.gradle.kts
=> Disable Maven Central snapshots repos

ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNext.kt
=> Fix opening 'track episode' from Up Next swipe

ios-app/Tivi/Settings.bundle/Root.plist, ios-app/Tivi/Tivi.xcodeproj/project.pbxproj
Mostly for vanity so it is displayed in Settings. Will likely add acknowledgements later.
=> Add version item to iOS Settings

ios-app/Tivi/Tivi/Auth.swift, ios-app/Tivi/Tivi/TiviApp.swift
=> Implement refresh token on iOS

common/ui/circuit-overlay/src/commonMain/kotlin/app/tivi/overlays/DialogOverlay.kt, ui/episode/details/src/commonMain/kotlin/app/tivi/episodedetails/EpisodeDetails.kt, ui/episode/track/src/commonMain/kotlin/app/tivi/episode/track/EpisodeTrack.kt, ui/episode/track/src/commonMain/kotlin/app/tivi/episode/track/EpisodeTrackPresenter.kt, ui/episode/track/src/commonMain/kotlin/app/tivi/episode/track/EpisodeTrackUiState.kt
=> Dismiss episode track dialog after submission

common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/Image.kt, ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNext.kt
The fade is distracting for a simple scroll up.
Fixes #1398
=> Don't crossfade images loaded from memory

thirdparty/swipe/src/commonMain/kotlin/me/saket/swipe/SwipeableActionsState.kt
Related: https://github.com/saket/swipe/issues/17
=> Disable swipe's overscroll

gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/KotlinMultiplatformConventionPlugin.kt
=> Enable iOS debug symbolication

data/db-sqldelight/src/iosMain/kotlin/app/tivi/data/SqlDelightDatabasePlatformComponent.kt
This adds a potential workaround for https://github.com/cashapp/sqldelight/issues/4376
=> Add potential workaround for SQLDelight crash

ui/root/src/iosMain/kotlin/app/tivi/home/GestureNavDecoration.kt
We now used a keyed DismissState, which helps us avoid the flash which happens after popping, which was caused by the race of `LaunchedEffect` vs composition.
=> iOS Gesture Nav improvements

data/db-sqldelight/src/jvmMain/kotlin/app/tivi/data/SqlDelightDatabasePlatformComponent.kt
We now a persistent SQLite database stored
in an appropriate place on each platform.
=> Persist Desktop database

data/traktauth/src/iosMain/kotlin/app/tivi/data/traktauth/IosAuthStore.kt
Avoids 'Keychain error -25308: User interaction is not allowed' when we try to refresh from the background on iOS.
=> Fix Keychain access from background

common/imageloading/src/androidMain/kotlin/app/tivi/common/imageloading/AndroidImageLoaderFactory.kt, common/imageloading/src/iosMain/kotlin/app/tivi/common/imageloading/IosImageLoaderFactory.kt, common/imageloading/src/jvmMain/kotlin/app/tivi/common/imageloading/DesktopImageLoaderFactory.kt, common/ui/compose/src/androidMain/kotlin/app/tivi/common/compose/ui/ColorMatrix.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/Image.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/ImageLoadingTreatment.kt, common/ui/compose/src/iosMain/kotlin/app/tivi/common/compose/ui/ColorMatrix.kt, common/ui/compose/src/jvmMain/kotlin/app/tivi/common/compose/ui/ColorMatrix.kt, shared/src/iosMain/kotlin/app/tivi/inject/IosApplicationComponent.kt
Spec'd and detailed here: https://m1.material.io/patterns/loading-images.html
=> Bring back the Material image loading treatment

common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/Modifier.kt, ui/root/src/iosMain/kotlin/app/tivi/home/GestureNavDecoration.kt
The hack to limit the swipe area was causing lots of issues so removing it for now.
=> Fix iOS gesture navigation glitches

gradle/build-logic/settings.gradle.kts, settings.gradle.kts
=> No need throwing if REMOTE_BUILD_CACHE_URL doesn't exist

gradle/build-logic/settings.gradle.kts, settings.gradle.kts
=> Add foojay toolchain resolver

common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/Image.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/ImageLoadingTreatment.kt
=> Use load time to determine whether to use image load transition

common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/Preference.kt, common/ui/resources/strings/src/commonMain/kotlin/app/tivi/common/ui/resources/EnTiviStrings.kt, common/ui/resources/strings/src/commonMain/kotlin/app/tivi/common/ui/resources/TiviStrings.kt, data/licenses/build.gradle.kts, data/licenses/src/androidMain/kotlin/app/tivi/data/licenses/LicenseDataPlatformComponent.kt, data/licenses/src/androidMain/kotlin/app/tivi/data/licenses/fetcher/AndroidLicensesFetcherImpl.kt, data/licenses/src/commonMain/kotlin/app/tivi/data/licenses/LicenseDataComponent.kt, data/licenses/src/commonMain/kotlin/app/tivi/data/licenses/LicensesState.kt, data/licenses/src/commonMain/kotlin/app/tivi/data/licenses/fetcher/LicensesFetcher.kt, data/licenses/src/commonMain/kotlin/app/tivi/data/licenses/store/LicensesStore.kt, data/licenses/src/commonMain/kotlin/app/tivi/data/licenses/store/LicensesStoreImpl.kt, data/licenses/src/iosMain/kotlin/app/tivi/data/licenses/LicenseDataPlatformComponent.kt, data/licenses/src/iosMain/kotlin/app/tivi/data/licenses/fetcher/IosLicensesFetcherImpl.kt, data/licenses/src/jvmMain/kotlin/app/tivi/data/licenses/LicenseDataPlatformComponent.kt, data/licenses/src/jvmMain/kotlin/app/tivi/data/licenses/fetcher/JvmLicensesFetcherImpl.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/FetchLicensesList.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/AndroidApplicationConventionPlugin.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/AndroidApplicationLicensesHandler.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/IosLicensesHandler.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/KotlinMultiplatformConventionPlugin.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/Licensee.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/task/AssetCopyTask.kt, gradle/libs.versions.toml, ios-app/Tivi/Tivi.xcodeproj/project.pbxproj, ui/licenses/src/commonMain/kotlin/app/tivi/settings/licenses/Licenses.kt, ui/licenses/src/commonMain/kotlin/app/tivi/settings/licenses/LicensesPresenter.kt, ui/licenses/src/commonMain/kotlin/app/tivi/settings/licenses/LicensesUiState.kt, ui/settings/src/commonMain/kotlin/app/tivi/settings/Settings.kt, ui/settings/src/iosMain/kotlin/app/tivi/settings/Platform.kt
We manually invoked a Licensee Gradle task from Xcode, and then copy in the JSON file into the app bundle.
=> Get open source licenses screen working on iOS

data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/daos/SqlDelightSeasonsDao.kt, data/db-sqldelight/src/commonMain/sqldelight/app/tivi/data/seasons.sq, data/models/src/commonMain/kotlin/app/tivi/data/compoundmodels/EpisodeWithWatches.kt
It's now a large 2d query, rather than a 3 level nested flat map.
=> Simplify seasonsWithEpisodesForShowId query

data/db-sqldelight/src/iosMain/kotlin/app/tivi/data/SqlDelightDatabasePlatformComponent.kt, gradle/libs.versions.toml, settings.gradle.kts
It contains a fix for https://github.com/cashapp/sqldelight/issues/4376. Testing that out without my workaround to verify the fix.
=> Try out SQLDelight 2.1.0-SNAPSHOT

common/ui/compose/build.gradle.kts, common/ui/compose/src/androidMain/kotlin/app/tivi/common/compose/Blur.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/Blur.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/EntryGrid.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/NestableScaffold.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/TiviScaffold.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/AppBar.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/PaddingValues.kt, common/ui/compose/src/skikoMain/kotlin/app/tivi/common/compose/Blur.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/ComposeMultiplatformConventionPlugin.kt, ui/developer/log/src/commonMain/kotlin/app/tivi/developer/log/DevLog.kt, ui/developer/settings/src/commonMain/kotlin/app/tivi/settings/developer/DevSettings.kt, ui/discover/src/commonMain/kotlin/app/tivi/home/discover/Discover.kt, ui/library/src/commonMain/kotlin/app/tivi/home/library/Library.kt, ui/licenses/src/commonMain/kotlin/app/tivi/settings/licenses/Licenses.kt, ui/root/src/commonMain/kotlin/app/tivi/home/Home.kt, ui/search/src/commonMain/kotlin/app/tivi/home/search/Search.kt, ui/settings/src/commonMain/kotlin/app/tivi/settings/Settings.kt, ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetails.kt, ui/show/seasons/src/commonMain/kotlin/app/tivi/showdetails/seasons/ShowSeasons.kt, ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNext.kt
Blur on Skia backed platforms (Desktop and iOS):
<video src="https://github.com/chrisbanes/tivi/assets/227486/0d1385bc-926d-4fb9-9752-058971f1798d" />
=> Overlay top and bottom bars

.github/workflows/build.yml
Seems that TestFlight is not setup for Xcode 15.0.1, so trying 15.0 explicitly.
https://developer.apple.com/forums/thread/740897
=> Revert to Xcode 15.0

.github/workflows/build.yml
Also split out iOS and Android publishing to different tasks
=> Go back to using Xcode 15.0.1

common/ui/compose/src/jvmCommon/kotlin/app/tivi/common/compose/ui/DateTimeDialogs.kt
=> Fix Date picker not updating the caller

common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/EntryGrid.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/HazeScaffold.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/NestedScaffold.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/PaddingValues.kt, ui/library/src/commonMain/kotlin/app/tivi/home/library/Library.kt, ui/search/src/commonMain/kotlin/app/tivi/home/search/Search.kt, ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetails.kt, ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNext.kt
We now use a custom WindowInsets instance to pass down the nested padding.
=> Simplify NestedScaffold

.github/workflows/build.yml, common/imageloading/build.gradle.kts, common/ui/compose/build.gradle.kts, common/ui/compose/src/iosMain/kotlin/app/tivi/common/compose/ui/DateTimeDialogs.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/Android.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/IosLicensesHandler.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/KotlinMultiplatformConventionPlugin.kt, ios-app/Tivi/Tivi.xcodeproj/project.pbxproj, ios-app/Tivi/Tivi.xcodeproj/xcshareddata/xcschemes/Tivi Prod.xcscheme, ios-app/Tivi/Tivi.xcodeproj/xcshareddata/xcschemes/Tivi QA.xcscheme, shared/prod/build.gradle.kts, shared/qa/build.gradle.kts, tasks/build.gradle.kts, tasks/src/iosMain/kotlin/app/tivi/tasks/IosShowTasks.kt
- Only create iOS frameworks for `:shared` modules
- Disable `release` Android unit tests
=> Build improvements

.github/workflows/build.yml
=> Try out new MacOS-14 runners

android-app/benchmark/build.gradle.kts
This has already been declared in the dependencies block
=> Remove declaration of junit dependency

common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/LogCompositions.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/BackdropCard.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/Image.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/PosterCard.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/TransformPainter.kt, ui/episode/details/src/commonMain/kotlin/app/tivi/episodedetails/EpisodeDetails.kt, ui/episode/track/src/commonMain/kotlin/app/tivi/episode/track/EpisodeTrack.kt, ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetails.kt, ui/show/seasons/src/commonMain/kotlin/app/tivi/showdetails/seasons/ShowSeasons.kt
- Remember image models
- Move image transition to draw phase
=> Improve image loading performance

common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/EntryGrid.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/LazyPagingExtensions.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/BackdropCard.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/Image.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/ImageLoadingTreatment.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/PosterCard.kt, compose-stability.conf, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/ComposeMultiplatformConventionPlugin.kt, ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetails.kt
Various issues which were leading to unnecessary recompositions.
=> Fix some Compose Stability issues

data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/columnadaptors/DayOfWeekColumnAdapter.kt, data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/columnadaptors/ImageTypeColumnAdapter.kt, data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/columnadaptors/PendingActionColumnAdapter.kt, data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/columnadaptors/RequestColumnAdapter.kt, data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/columnadaptors/ShowStatusColumnAdapter.kt, data/models/src/commonMain/kotlin/app/tivi/data/models/Genre.kt
https://kotlinlang.org/docs/enum-classes.html#working-with-enum-constants
=> Migrate to using Kotlin's new Enum entries

android-app/app/proguard-rules.pro
- https://github.com/square/retrofit/releases/tag/2.10.0
- https://issuetracker.google.com/issues/265188224#comment17
=> Remove outdated proguard rules

desktop-app/build.gradle.kts, gradle/libs.versions.toml
=> desktop: Fix the missing main dispatcher for Coroutines

core/base/src/commonMain/kotlin/app/tivi/util/Collections.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateLibraryShows.kt
Currently we only fetch watched shows, which isn't great for shows which haven't been watched yet by the user.
=> Fetch season/episodes for followed shows too

common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/EntryGrid.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/Clickable.kt, ui/discover/src/commonMain/kotlin/app/tivi/home/discover/Discover.kt, ui/library/src/commonMain/kotlin/app/tivi/home/library/Library.kt, ui/search/src/commonMain/kotlin/app/tivi/home/search/Search.kt, ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetails.kt, ui/show/seasons/src/commonMain/kotlin/app/tivi/showdetails/seasons/ShowSeasons.kt, ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNext.kt
It's an iOS UX pattern, but it's a good one.
=> Scroll to top on app bar clicks

domain/src/commonMain/kotlin/app/tivi/domain/Interactor.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateEpisodeDetails.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateLibraryShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdatePopularShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateRecommendedShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateRelatedShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateShowDetails.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateShowImages.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateShowSeasons.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateTrendingShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateUpNextEpisodes.kt, domain/src/commonMain/kotlin/app/tivi/domain/interactors/UpdateUserDetails.kt, domain/src/commonMain/kotlin/app/tivi/domain/observers/ObservePagedPopularShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/observers/ObservePagedRecommendedShows.kt, domain/src/commonMain/kotlin/app/tivi/domain/observers/ObservePagedTrendingShows.kt, ui/discover/src/commonMain/kotlin/app/tivi/home/discover/Discover.kt, ui/discover/src/commonMain/kotlin/app/tivi/home/discover/DiscoverPresenter.kt, ui/discover/src/commonMain/kotlin/app/tivi/home/discover/DiscoverUiState.kt, ui/episode/details/src/commonMain/kotlin/app/tivi/episodedetails/EpisodeDetailsUiState.kt, ui/episode/track/src/commonMain/kotlin/app/tivi/episode/track/EpisodeTrackUiState.kt, ui/library/src/commonMain/kotlin/app/tivi/home/library/LibraryUiState.kt, ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetailsUiState.kt, ui/show/seasons/src/commonMain/kotlin/app/tivi/showdetails/seasons/ShowSeasons.kt, ui/show/seasons/src/commonMain/kotlin/app/tivi/showdetails/seasons/ShowSeasonsUiState.kt, ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNext.kt, ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNextUiState.kt
We now only show loading indicators from ambient loads after 5 seconds
=> Debounce loading indicators

common/ui/compose/build.gradle.kts, common/ui/compose/src/androidMain/kotlin/app/tivi/common/compose/Coil.kt, common/ui/compose/src/androidMain/kotlin/app/tivi/common/compose/ColorExtractor.android.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ColorExtractor.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/TiviCompositionLocals.kt, common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/TiviPreferenceExtensions.kt, common/ui/compose/src/iosMain/kotlin/app/tivi/common/compose/Coil.kt, common/ui/compose/src/iosMain/kotlin/app/tivi/common/compose/ColorExtractor.ios.kt, common/ui/compose/src/jvmMain/kotlin/app/tivi/common/compose/Coil.kt, common/ui/compose/src/jvmMain/kotlin/app/tivi/common/compose/ColorExtractor.jvm.kt, gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/Licensee.kt, gradle/libs.versions.toml, ui/discover/src/commonMain/kotlin/app/tivi/home/discover/Discover.kt, ui/root/src/commonMain/kotlin/app/tivi/home/TiviContent.kt
Currently only on the discover 'up next' cards, but there's more places we can use it
=> Early experiements with color extraction

android-app/app/src/main/kotlin/app/tivi/home/MainActivity.kt, core/analytics/src/commonMain/kotlin/app/tivi/core/analytics/AnalyticsInitializer.kt, core/logging/implementation/src/commonMain/kotlin/app/tivi/util/CrashReportingInitializer.kt, core/preferences/src/commonMain/kotlin/app/tivi/settings/Preference.kt, core/preferences/src/commonMain/kotlin/app/tivi/settings/TiviPreferencesImpl.kt
Should help with preferences always starting from the default value
=> Read Preference into a StateFlow

android-app/app/src/main/kotlin/app/tivi/home/MainActivity.kt
| Before | After |
|--------|--------|
| ![before](https://github.com/user-attachments/assets/3ac11a64-313b-4a42-9cbd-fdc42e7d4b78) | ![after](https://github.com/user-attachments/assets/0f647c6f-97af-4155-ad96-f30d97c34ef2) |
=> Fix edge-to-edge on three-button nav bar

android-app/app/build.gradle.kts, android-app/app/proguard-rules.pro, core/entitlements/core/build.gradle.kts, core/entitlements/ui/build.gradle.kts
We don't need it, so no point incurring the cost
=> Exclude Amazon SDK
