- app/src/main/java/me/banes/chris/tivi/ui/TiviShowGridAdapter.kt
I fixed to use nested class instead of inner class.
Because `DiffCb` class doesn't need to access members of outer class.
Here is the official reference.
https://kotlinlang.org/docs/reference/nested-classes.html
> Fix to use nested class

- app/src/main/res/layout/header_item.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Makes it clearer for users that the header can be clicked and looks similar to how the Google Play Store app does that.
> Add 'More' label to list header

- app/src/main/java/me/banes/chris/tivi/home/HomeActivity.kt
- app/src/main/java/me/banes/chris/tivi/home/discover/DiscoverFragment.kt
- app/src/main/java/me/banes/chris/tivi/home/library/LibraryFragment.kt
Scrolls the `RecyclerView` to the top when the bottom navigation tab is clicked and the backstack is empty. There should be a better way to do this than using `supportFragmentManager.fragments[1]` to get the current fragment.
> Scroll to top when bottom navigation is clicked

- app/src/main/java/me/banes/chris/tivi/data/daos/TrendingDao.kt
- app/src/main/java/me/banes/chris/tivi/ui/ShowPosterGridAdapter.kt
Was caused by the loading progress bar logic
removing actual items
Also made the sort for trending items stable
> Fix random re-ordering in grids

- .circleci/config.yml
The `check` task used to build APKs, but no more it seems...
> Explicitly build APKs on CI

- build.gradle
- spotless/copyright.kt
So that we can use it's new $YEAR copyright
tag
> Update to Spotless 3.8.0

- app/build.gradle
Causing too many slows down while debugging transitions.
> Move LeakCanary out to different variant

- tmdb/src/main/java/me/banes/chris/tivi/tmdb/TmdbImageUrlProvider.kt
This PR fixes #106 the NPE in TmdbImageUrlProvider where `previousUrl` is null but is accessed with `previousUrl!!`.
It also replaces the parsing of the size with regex - I can revert this since this fixes something that will only manifest as a bug if TMDB changes their size format (e.g. from `w72` to `72w` or `w72px`).
> 106/Fix NPE in TmdbImageUrlProvider

- build.gradle
We still need jcenter, but it is a lower priority than Maven Central
> Use Maven Central over jcenter

- data/build.gradle
This is 10% OSS contribution stuff and 90% me guinea pigging this project to make sure the new release worked somewhere other than my own pet project :)
https://github.com/hzsweers/copydynamic/blob/master/CHANGELOG.md#version-013
TL;DR: fix a name collision if there was a property also named `source` and shade kotlinpoet/autocommon dependencies to avoid potential conflicts.
> Update CopyDynamic to 0.1.3

- checksum.sh
Backtick command substitution `...` is legacy syntax with several issues.
- It has a series of undefined behaviors related to quoting in POSIX.
- It imposes a custom escaping mode with surprising results.
- It's exceptionally hard to nest.
$(...) command substitution has none of these problems, and is therefore strongly encouraged.
> Use $(...)  instead of legacy backticks for checksum.sh

- app/build.gradle
- build.gradle
`serviceAccountCredentials` configuration can be specified more succinctly.
Since there is no flavor-specific setup right now, I think it's reasonable to use the simpler way.
> Update Play Publisher and simplify its configuration

- app/build.gradle
New `enabled` [flag](https://github.com/KeepSafe/dexcount-gradle-plugin#configuration) was introduced in v0.8.4, which explicitly enables/disables counting, so it makes sense to use it for this purpose.
>enabled: When false, no build outputs will be counted. Defaults to true.
> Use dexcount 'enabled' flag to run it only on CI

- .idea/misc.xml
- .idea/modules.xml
- app/build.gradle
- cloudbuild.yaml
- cloudbuild/android/Dockerfile
- cloudbuild/android/README.md
- cloudbuild/android/cloudbuild.yaml
- cloudbuild/cloudbuild.yaml
- cloudbuild/setup_env.sh
- cloudbuild/tar/Dockerfile
- cloudbuild/tar/README.md
- cloudbuild/tar/cloudbuild.yaml
I've done a lot of work on the cloud builders since you started the integration, so here's the updated build script.
This is mostly functional, minus the deployment data since I don't have access to your keys.
Setup is much easier than before, simply: 
0. Setup `gcloud`, etc.
1. Install the cloud builders.
```bash
git clone git@github.com:pixiteapps/android-cloud-build /tmp/android-cloud-build
cd /tmp/android-cloud-build
gcloud builds submit .
```
2. Setup GCS buckets for cache, config and artifacts and update substitutions (via `--substitutions` works).
```yaml
_ARTIFACT_BUCKET: black-circle-221-tivi-build-artifacts
_CACHE_BUCKET: black-circle-221-tivi-build-cache
_CONFIG_BUCKET: black-circle-221-tivi-build-config
```
This should still probably be considered experimental as it takes …
> Google Cloud Build implementation

- .idea/misc.xml
- .idea/modules.xml
- app/build.gradle
- cloudbuild.yaml
- cloudbuild/android/Dockerfile
- cloudbuild/android/README.md
- cloudbuild/android/cloudbuild.yaml
- cloudbuild/cloudbuild.yaml
- cloudbuild/setup_env.sh
- cloudbuild/tar/Dockerfile
- cloudbuild/tar/README.md
- cloudbuild/tar/cloudbuild.yaml
> Google Cloud Build (following #271)

- app/build.gradle
I think the proper verification is to check if the `app-release.jks` file exists for release build.
> Verify with the proper keystore for release build

- gradle.properties
Gradle 5.0 change the default memory from 1g to 512m. This caused failed build with `OutOfMemoryError: GC overhead limit exceeded` error. Setting back the memory to 1g fix this issue. See https://github.com/gradle/gradle/issues/7746#issuecomment-439137327
> Fix OutOfMemoryError when building the first time

- checksum.sh
Hey, I used the same script on an integration for CloudBuild and noticed that the `checksum.sh` was not working correctly. This PR fixes it 😃
> Fix checksum script

- buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt
- data-android/src/main/java/app/tivi/data/FlowPagedListBuilder.kt
- interactors/build.gradle
- interactors/src/main/java/app/tivi/interactors/ObservePagedFollowedShows.kt
- interactors/src/main/java/app/tivi/interactors/ObservePagedPopularShows.kt
- interactors/src/main/java/app/tivi/interactors/ObservePagedTrendingShows.kt
- interactors/src/main/java/app/tivi/interactors/ObservePagedWatchedShows.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
Allows us to move away from RxPagedListBuilder.
May not be a perfect port of RxPagedListBuilder, but it's close enough.
> Move paged interactors to use Flow directly

- app/src/main/java/app/tivi/home/HomeActivityViewModel.kt
- app/src/main/java/app/tivi/inject/AppModule.kt
- base/src/main/java/app/tivi/inject/Annotations.kt
- common-entrygrid/src/main/java/app/tivi/util/EntryViewModel.kt
- ui-discover/src/main/java/app/tivi/home/discover/DiscoverViewModel.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewModel.kt
- ui-followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt
- ui-popular/src/main/java/app/tivi/home/popular/PopularShowsViewModel.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt
- ui-trending/src/main/java/app/tivi/home/trending/TrendingShowsViewModel.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
We now inject a CoroutineScope which is based off the ProcessLifecycleOwner lifecycle, meaning that the operations will not be cancelled prematurely. Flow/observable subscriptions still happen within the `viewModelScope`.
Closes #360
> Use process scope for long-lived operations

- interactors/src/main/java/app/tivi/interactors/Interactor.kt
Since we're now using a potentially longer lived scope for data operations (#397), we need to make sure we don't leak any ViewModel members.
Fixed by wrapping the `ObservableLoadingCounter` to a `WeakReference`.
> Fix potential memory leak

- common-glide/src/main/java/app/tivi/ui/glide/GlideBindingAdapters.kt
They now only request if the parameters have actually changed. This stops the random flickering happening due to state emissions during scrolling.
> Fix Glide binding adapters

- base/src/main/java/app/tivi/base/InvokeStatus.kt
- base/src/main/java/app/tivi/data/entities/Result.kt
- common-entrygrid/src/main/java/app/tivi/util/EntryViewModel.kt
- common-ui/src/main/java/app/tivi/util/ObservableLoadingCounter.kt
- data/src/main/java/app/tivi/data/repositories/episodes/SeasonsEpisodesRepository.kt
- data/src/main/java/app/tivi/data/repositories/followedshows/FollowedShowsRepository.kt
- data/src/main/java/app/tivi/data/repositories/followedshows/TraktFollowedShowsDataSource.kt
- data/src/main/java/app/tivi/data/repositories/popularshows/PopularShowsRepository.kt
- data/src/main/java/app/tivi/data/repositories/recommendedshows/RecommendedShowsRepository.kt
- data/src/main/java/app/tivi/data/repositories/relatedshows/RelatedShowsRepository.kt
- data/src/main/java/app/tivi/data/repositories/shows/ShowRepository.kt
- data/src/main/java/app/tivi/data/repositories/shows/TraktShowDataSource.kt
- data/src/main/java/app/tivi/data/repositories/traktusers/TraktUsersRepository.kt
- data/src/main/java/app/tivi/data/repositories/trendingshows/TrendingShowsRepository.kt
- data/src/main/java/app/tivi/data/repositories/watchedshows/WatchedShowsRepository.kt
- domain/src/main/java/app/tivi/domain/Interactor.kt
- Use async instead of launch, so that we can actually catch exceptions.
- We now have an InvokeError state for interactors
- Update followed show list fetch to catch throwables rather than just IOExceptions
> More exception handling improvements

- data/src/main/java/app/tivi/data/repositories/episodes/SeasonsEpisodesRepository.kt
The watch time is the start of the watch, not
the end
> Stop adding 1 hour onto episode watches

- .circleci/config.yml
Lint is memory hungry so we want to make sure that it is running on it's own, not potentially with tests running too, etc.
> Split out lint task on CI

- common-entrygrid/src/main/java/app/tivi/util/EntryGridEpoxyController.kt
- common-entrygrid/src/main/java/app/tivi/util/EntryGridFragment.kt
- common-entrygrid/src/main/java/app/tivi/util/EntryViewModel.kt
- common-entrygrid/src/main/java/app/tivi/util/EntryViewState.kt
- ui-followed/src/main/java/app/tivi/home/followed/FollowedFragment.kt
- ui-followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt
- ui-followed/src/main/java/app/tivi/home/followed/FollowedViewState.kt
- ui-popular/src/main/java/app/tivi/home/popular/PopularShowsViewModel.kt
- ui-recommended/src/main/java/app/tivi/home/recommended/RecommendedShowsViewModel.kt
- ui-trending/src/main/java/app/tivi/home/trending/TrendingShowsViewModel.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedFragment.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedViewState.kt
MvRxStates are designed to be completely immutable, which conflicts with PagedLists which are very mutable.
This commit moves the paged lists out of the MvRxStates, and to their own Flow, which each Fragment collects separately.
Closes #517
> Move PagedLists out of MvRx states

- base-android/src/main/java/app/tivi/extensions/ContextExtensions.kt
They're wrongly named and  not used anyway.
Closes #521
> Remove toDp() extfuns

- .github/workflows/main.yml
On master we call `publishRelease`, which will automatically build the release variant. If we do both `assembleRelease` and `publishRelease` on master, we're running R8 twice, which is wasteful.
> Only run assembleRelease on feature branches

- gradle.properties
Avoid "GC overhead limit exceeded" error while building. If this is not specified it should default to 1 GB, I wasn't able to run tivi without this.
> Increase java heap size to 2 GB

- app/src/main/res/navigation/show_details_nav_graph.xml
- common-epoxy/src/main/java/app/tivi/common/epoxy/EpoxyExtensions.kt
- common-ui/src/main/java/app/tivi/extensions/AnimatorExtensions.kt
- common-ui/src/main/java/app/tivi/extensions/MotionLayoutExtensions.kt
- common-ui/src/main/java/app/tivi/extensions/RecyclerViewExtensions.kt
- common-ui/src/main/java/app/tivi/extensions/ViewExtensions.kt
- common-ui/src/main/java/app/tivi/ui/widget/TiviMotionLayout.kt
- common-ui/src/main/res/drawable/ic_add_24dp.xml
- common-ui/src/main/res/values/ids.xml
- data/src/main/java/app/tivi/data/repositories/episodes/SeasonsEpisodesRepository.kt
- domain/src/main/java/app/tivi/domain/Interactor.kt
- domain/src/main/java/app/tivi/domain/interactors/GetEpisodeDetails.kt
- ui-discover/src/main/java/app/tivi/home/discover/DiscoverFragment.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsActions.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsFragment.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewModel.kt
- ui-episodedetails/src/main/res/layout/fragment_episode_details.xml
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsViewState.kt
All actions and state changes are now provided through the ViewModel and it's state observable.
Since we've now centralised the logic, opening the new episode to watch from 'Discover' now correctly deeplinks to the episode.
> Update show details to use `Action`

- .github/workflows/build.yml
Cache v1.1.0 supports caches up to 2GB, which should be enough for the entire Gradle cache folder.
> Update to cache v1.1.0

- .github/workflows/build.yml
- .github/workflows/release-management.yml
- .github/workflows/scheduled.yml
- Use `$GITHUB_RUN_NUMBER` for version code
- Add timeout to cache action
- Split out dependency update check to nightly task
- Collapse most of release tasks into main build step
> GitHub Actions improvements

- common-ui-view/src/main/res/values/attrs.xml
No need of workaround for ConstraintLayout as issue has been fixed already. Also, using the latest version of constraintLayout 2.0.0-beta4.
**Reference revision:**
Update to AGP 3.6.0-alpha12
Required a workaround for ConstraintLayout
Revision - f57a8e10332dccc0c5f9bc3f325244dbe367c883
> No need of workaround for ConstraintLayout as issue has been fixed already

- app/src/main/AndroidManifest.xml
- data/src/main/java/app/tivi/data/repositories/episodes/TraktSeasonsEpisodesDataSource.kt
- trakt-auth/src/main/java/app/tivi/trakt/TraktAuthModule.kt
- trakt-auth/src/main/java/app/tivi/trakt/TraktManager.kt
- trakt/src/main/java/app/tivi/trakt/TraktModule.kt
Currently we do not pass in the client secret or redirect URI to TraktV2, which means that the auto token
is never refreshed.
This commit fixes that by passing through the correct information, to enable TraktV2 to refresh the token as necessary.
> Setup TraktV2 for automatic refresh tokens

- .github/ci-gradle.properties
It was previously disabled on CI due to memory pressure, but that is no
longer an issue on GitHub Actions.
> Re-enable Kotlin incremental compilation

- app/src/main/java/app/tivi/util/AndroidPowerController.kt
Due to ConnectivityManagerCompat using a fallback value of 'restricted' pre API 24.
> Fix data-saver always being enabled on API 23

- base/src/main/java/app/tivi/extensions/CoroutineExtensions.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateFollowedShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdatePopularShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateRecommendedShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateRelatedShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateTrendingShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateWatchedShows.kt
We will eventually be able to use the (hopefully) upcoming parallel operator.
> Use asFlow() to process lists instead of parallelMap

- app/src/main/java/app/tivi/home/HomeActivityViewModel.kt
- buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt
- common-entrygrid/src/main/java/app/tivi/util/EntryViewModel.kt
- common-ui-view/src/main/java/app/tivi/ReduxViewModel.kt
- common-ui-view/src/main/java/app/tivi/extensions/ViewModelExtensions.kt
- ui-account/src/main/java/app/tivi/account/AccountUiViewModel.kt
- ui-discover/src/main/java/app/tivi/home/discover/DiscoverFragment.kt
- ui-discover/src/main/java/app/tivi/home/discover/DiscoverViewModel.kt
- ui-episodedetails/build.gradle
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsFragment.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsInject.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewModel.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewState.kt
- ui-followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt
- ui-search/src/main/java/app/tivi/home/search/SearchViewModel.kt
- ui-showdetails/build.gradle
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentInject.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsViewState.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
When we moved to Hilt, I removed the `AssistedInject`ed initial state to aid migration. This PR adds it back in for the ViewModels which need an initial state (show details and episode details).
I've also moved all of the other ViewModels to pass in their initial state via a constructor param. If any of those ViewModels need some init state in the future it will be easy to add.
> Start injecting the initial ViewModel state again

- domain/src/main/java/app/tivi/domain/interactors/UpdateFollowedShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdatePopularShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateRecommendedShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateRelatedShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateShowSeasonData.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateTrendingShows.kt
- domain/src/main/java/app/tivi/domain/interactors/UpdateWatchedShows.kt
Ensures that the long running interactors will cancel cooperatively.
> Use `yield()` and `ensureActive()`

- base-android/src/main/java/app/tivi/util/BroadcastReceiverFlow.kt
- base/src/main/java/app/tivi/inject/Annotations.kt
- buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt
- common-entrygrid/src/main/java/app/tivi/util/EntryViewModel.kt
- common-ui-view/build.gradle
- common-ui-view/src/main/java/app/tivi/ReduxViewModel.kt
- common-ui-view/src/main/java/app/tivi/ui/SnackbarManager.kt
- common-ui-view/src/main/java/app/tivi/util/ObservableLoadingCounter.kt
- common-ui-view/src/main/java/app/tivi/util/ShowStateSelector.kt
- data-android/src/main/java/app/tivi/data/DatabaseInject.kt
- data-android/src/main/java/app/tivi/data/repositories/popularshows/PopularShowsModule.kt
- data-android/src/main/java/app/tivi/data/repositories/recommendedshows/RecommendedShowsModule.kt
- data-android/src/main/java/app/tivi/data/repositories/relatedshows/RelatedShowsModule.kt
- data-android/src/main/java/app/tivi/data/repositories/showimages/ShowsImagesModule.kt
- data-android/src/main/java/app/tivi/data/repositories/shows/ShowsModule.kt
- data-android/src/main/java/app/tivi/data/repositories/trendingshows/TrendingShowsModule.kt
- data-android/src/main/java/app/tivi/data/repositories/watchedshows/WatchedShowsModule.kt
- domain/src/main/java/app/tivi/domain/Interactor.kt
- tmdb/src/main/java/app/tivi/tmdb/TmdbManager.kt
- trakt-auth/src/main/java/app/tivi/trakt/TraktManager.kt
- ui-account/src/main/java/app/tivi/account/AccountUiFragment.kt
- ui-account/src/main/java/app/tivi/account/AccountUiViewModel.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsFragment.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewModel.kt
- ui-followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt
- ui-search/src/main/java/app/tivi/home/search/SearchViewModel.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragment.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsFragmentViewModel.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
- Updated to Coroutines 1.3.7
- Replaced all usage of `ConflatedBroadcastChannel` with `StateFlow`
- Started consuming `pendingAction` Channels in ViewModels via `consumeAsFlow()` to ensure the channels get closed.
- Started checking for closed channels before `offer()`ing
- Tidied up some of the internals of `ReduxViewModel` since we can now rely on `StateFlow`
- Removed `Store`'s explicit `CoroutineScope`
> Lots of improvements around Coroutines usage

- domain/src/main/java/app/tivi/domain/Interactor.kt
Semantically almost identical but more fluent in terms of Kotlin code.
> Uses flow's catch instead

- data/src/main/java/app/tivi/data/entities/Episode.kt
- data/src/main/java/app/tivi/data/resultentities/EpisodeWithWatches.kt
- data/src/main/java/app/tivi/data/resultentities/SeasonWithEpisodesAndWatches.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsTextCreator.kt
Currently we pass down entire data classes to composable functions. These classes are backed by a changing data source
(Room) which means that if any field changes, all composable functions which have a data class param which re-compose.
We can help with that by deconstructing the params and only passing in the bare minimum each composable needs
> Improvements across composability in show details 

- app/src/main/AndroidManifest.xml
- trakt-auth/src/main/java/app/tivi/trakt/TraktAuthModule.kt
https://github.com/openid/AppAuth-Android/issues/599
> Fix login due to Trakt and TargetSdk 30 changes

- .github/workflows/build.yml
- build.gradle
- buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt
Includes workaround for https://github.com/Triple-T/gradle-play-publisher/issues/864, which means we can upgrade AGP to 4.2.0-alpha13
> Use Gradle Play Publisher SNAPSHOT

- common-imageloading/src/main/java/app/tivi/common/imageloading/CoilAppInitializer.kt
Since we're not using transitions right now
> Re-enable hardware bitmaps

- buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt
- domain/src/main/java/app/tivi/domain/Interactor.kt
Reverts the behavior to what we had previously with `BroadcastChannel`s.
Closes #721
> Move to SharedFlow in SubjectInteractor

- base/src/main/java/app/tivi/extensions/CoroutineExtensions.kt
- buildSrc/src/main/java/app/tivi/buildsrc/dependencies.kt
- common-ui-view/src/main/java/app/tivi/util/ObservableLoadingCounter.kt
- data/src/main/java/app/tivi/data/StoreExtensions.kt
- data/src/main/java/app/tivi/data/repositories/episodes/SeasonsEpisodesRepository.kt
- data/src/main/java/app/tivi/data/repositories/followedshows/FollowedShowsRepository.kt
- data/src/main/java/app/tivi/data/repositories/traktusers/TraktUsersRepository.kt
- domain/src/main/java/app/tivi/domain/observers/ObserveShowDetails.kt
- domain/src/main/java/app/tivi/domain/observers/ObserveShowImages.kt
- Removed our `asyncOrAwat()` functionality. It's no longer needed now that we're using Store with its multiplexer.
- Fixed the loading counter not removing the loader when the coroutine is cancelled.
- Fixed a crash caused by not filtering for Store's loading state.
- Update Store to 4.0.0
> Some small performance improvements and bug fixes

- trakt-auth/src/main/java/app/tivi/trakt/TraktAuthModule.kt
As I have described the problem https://github.com/chrisbanes/tivi/issues/747, there was a problem in compiling code. current code called AuthorizationServiceConfiguration with three parameters but it has constructors with two or four parameters.
> Fix TraktAuthModule compile error

- build.gradle
- buildSrc/src/main/java/app/tivi/buildsrc/DependencyUpdates.kt
We now only report dependency updates which are meet our update criteria. Specifically we now reject all candidates which are 'less stable' than the version which are explicitly currently using.
Example: If set a dependency to be `2.0.0-beta01`, we now reject `2.1.0-alpha01`
> Add custom versioning policy for `dependencyUpdates`

- README.md
I noticed the play store link was redirecting back to the GitHub repo.
> Fix Play store link

- app/proguard-rules.pro
This reduces uncompressed dex size by ~4%.
> Remove redundant rules in shrinker configuration

- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt
I've noticed the favorite icon behaves differently (showing enabled state for disabled and vice versa)
> Fix flipped fav icon (UX)

- app/build.gradle
- app/proguard-rules-chucker.pro
- build.gradle
Chucker uses GSON and TypeToken so we need to keep various classes: https://r8.googlesource.com/r8/+/refs/heads/main/compatibility-faq.md#gson-with-full-mode
> Fix Chucker not working with R8 full mode enabled

- .github/workflows/build.yml
- app/build.gradle
Allows controlling of the version code, which is necessary to ship both to Play Store on different tracks.
> Move QA build type to a flavour

- base/src/main/java/app/tivi/extensions/RetrofitExtensions.kt
- data-android/src/test/java/app/tivi/data/repositories/FollowedShowRepositoryTest.kt
- data/src/main/java/app/tivi/data/mappers/Mapper.kt
- data/src/main/java/app/tivi/data/repositories/episodes/TmdbEpisodeDataSource.kt
- data/src/main/java/app/tivi/data/repositories/episodes/TraktEpisodeDataSource.kt
- data/src/main/java/app/tivi/data/repositories/episodes/TraktSeasonsEpisodesDataSource.kt
- data/src/main/java/app/tivi/data/repositories/followedshows/FollowedShowsDataSource.kt
- data/src/main/java/app/tivi/data/repositories/followedshows/FollowedShowsRepository.kt
- data/src/main/java/app/tivi/data/repositories/followedshows/TraktFollowedShowsDataSource.kt
- data/src/main/java/app/tivi/data/repositories/popularshows/TraktPopularShowsDataSource.kt
- data/src/main/java/app/tivi/data/repositories/recommendedshows/TraktRecommendedShowsDataSource.kt
- data/src/main/java/app/tivi/data/repositories/relatedshows/TmdbRelatedShowsDataSource.kt
- data/src/main/java/app/tivi/data/repositories/relatedshows/TraktRelatedShowsDataSource.kt
- data/src/main/java/app/tivi/data/repositories/search/TmdbSearchDataSource.kt
- data/src/main/java/app/tivi/data/repositories/showimages/TmdbShowImagesDataSource.kt
- data/src/main/java/app/tivi/data/repositories/shows/TmdbShowDataSource.kt
- data/src/main/java/app/tivi/data/repositories/shows/TraktShowDataSource.kt
- data/src/main/java/app/tivi/data/repositories/traktusers/TraktUsersDataSource.kt
- data/src/main/java/app/tivi/data/repositories/trendingshows/TraktTrendingShowsDataSource.kt
- data/src/main/java/app/tivi/data/repositories/watchedshows/TraktWatchedShowsDataSource.kt
- gradle/libs.versions.toml
- tmdb/src/main/java/app/tivi/tmdb/TmdbManager.kt
We now catch IOExceptions properly which are thrown from
Retrofit calls.
> Fix exception handling in network requests

- app/src/main/java/app/tivi/home/Home.kt
- app/src/main/java/app/tivi/home/MainActivity.kt
- app/src/main/java/app/tivi/inject/AppModule.kt
- app/src/main/java/app/tivi/inject/AppModuleBinds.kt
- base-android/build.gradle
- base-android/src/main/java/app/tivi/BaseModule.kt
- base-android/src/main/java/app/tivi/util/TiviAnalytics.kt
- base-android/src/main/java/app/tivi/util/TiviLogger.kt
- base/src/main/java/app/tivi/util/Analytics.kt
- base/src/main/java/app/tivi/util/Logger.kt
- data-android/src/test/java/app/tivi/data/TestDatabaseInject.kt
We currently don't have a way to set Destination labels in Compose
though unfortunately.
> Re-add screen view analytics events

- domain/src/main/java/app/tivi/domain/interactors/SearchShows.kt
Currently we wrap all exceptions from showFtsDao.search() in
a IAE, but that then hides any CancellationExceptions and they
show up as crashes. Fixed by only catching SQLiteExceptions.
> Stop wrapping child cancellation exceptions from search

- common-ui-view/src/main/java/app/tivi/api/UiMessage.kt
- ui-discover/src/main/java/app/tivi/home/discover/Discover.kt
- ui-discover/src/main/java/app/tivi/home/discover/DiscoverViewModel.kt
- ui-discover/src/main/java/app/tivi/home/discover/DiscoverViewState.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewModel.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewState.kt
- ui-followed/src/main/java/app/tivi/home/followed/Followed.kt
- ui-followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt
- ui-followed/src/main/java/app/tivi/home/followed/FollowedViewState.kt
- ui-search/src/main/java/app/tivi/home/search/Search.kt
- ui-search/src/main/java/app/tivi/home/search/SearchViewModel.kt
- ui-search/src/main/java/app/tivi/home/search/SearchViewState.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsViewModel.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsViewState.kt
- ui-showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasons.kt
- ui-showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasonsViewModel.kt
- ui-showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasonsViewState.kt
- ui-watched/src/main/java/app/tivi/home/watched/Watched.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
- ui-watched/src/main/java/app/tivi/home/watched/WatchedViewState.kt
Follow on from #889. 
Previously each view state would contain a list of the queued up messages. This means that the UI is responsible for deciding what message to display, which is a bit too much logic in the UI for my liking.
This PR changes this so each view state contains a single `UiMessage?`. The queuing is moved to `UiMessageManager` which means that all of the logic is still in the VM. We could later add some kind of message prioritisation, skip messages, etc later without any changes to the UI.
WDYT @manuelvicnt?
> UIs now only receive a single UiMessage to display

- common-ui-compose/src/main/java/app/tivi/common/compose/FlowWithLifecycle.kt
- ui-account/src/main/java/app/tivi/account/AccountUi.kt
- ui-discover/src/main/java/app/tivi/home/discover/Discover.kt
- ui-episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt
- ui-followed/src/main/java/app/tivi/home/followed/Followed.kt
- ui-search/src/main/java/app/tivi/home/search/Search.kt
- ui-showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt
- ui-showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasons.kt
- ui-watched/src/main/java/app/tivi/home/watched/Watched.kt
Minor cleanup and simplification of initial value which exists from StateFlow.
I was using your implementation, but wanted to avoid passing in an extra initial value,
and figured worth pushing back to here.  No problem if not desired, but I'd love to here your
take if so.
> rememberStateWithLifecycle utility

- trakt-auth/src/main/java/app/tivi/trakt/ActivityTraktAuthManager.kt
- trakt-auth/src/main/java/app/tivi/trakt/TraktAuthManager.kt
There is a massive UI lag when opening the AccountUi dialog, which is caused by the AppAuth's `AuthorizationService`:
> AuthorizationService will create a bound service connection to the browser in order to perform a "warm up" that makes the custom tab load faster. As such, you should create your AuthorizationService instance early in your activity's lifecycle to benefit from this warmup, and not at the moment at which you click "sign in".\
[https://github.com/openid/AppAuth-Android/issues/328](https://github.com/openid/AppAuth-Android/issues/328)
As of now, `ActivityTraktAuthManager::buildLoginIntent` is called right after AccountUi dialog is opened.\
I modified `LoginTrakt` and `TraktAuthManager` such that `buildLoginIntent` is only called after user clicks the login button and the …
> Fix AccountUi lag

- app/proguard-rules.pro
- gradle/libs.versions.toml
They now contain the necessary R8 rules so we can remove our manual rules.
> Upgrade tmdb-java and trakt-java

- base/src/main/java/app/tivi/extensions/Lazy.kt
- data-android/src/main/java/app/tivi/data/TiviTypeConverters.kt
- data/src/main/java/app/tivi/data/entities/ShowImages.kt
- data/src/main/java/app/tivi/data/entities/TiviShow.kt
- data/src/main/java/app/tivi/data/resultentities/EpisodeWithSeasonWithShow.kt
- data/src/main/java/app/tivi/data/resultentities/FollowedShowEntryWithShow.kt
- data/src/main/java/app/tivi/data/resultentities/PopularEntryWithShow.kt
- data/src/main/java/app/tivi/data/resultentities/RecommendedEntryWithShow.kt
- data/src/main/java/app/tivi/data/resultentities/RelatedShowEntryWithShow.kt
- data/src/main/java/app/tivi/data/resultentities/ShowDetailed.kt
- data/src/main/java/app/tivi/data/resultentities/TrendingEntryWithShow.kt
- data/src/main/java/app/tivi/data/resultentities/WatchedShowEntryWithShow.kt
Like: https://github.com/runningcode/kotlin-dsl/blob/master/subprojects/provider/src/main/kotlin/org/gradle/kotlin/dsl/support/unsafeLazy.kt
> Add `unsafeLazy` to simplify thread unsafe lazy initializations

- gradle.properties
- Remove -XX:+UseParallelGC and use the default garbage collector as the improvements are minimal on JDK 17+
- https://docs.gradle.org/7.0.1/release-notes.html#file-system-watching
> Minor flags tweak

- ui/account/src/main/java/app/tivi/account/AccountUi.kt
- ui/account/src/main/java/app/tivi/account/AccountUiViewModel.kt
- ui/discover/src/main/java/app/tivi/home/discover/Discover.kt
- ui/discover/src/main/java/app/tivi/home/discover/DiscoverViewModel.kt
- ui/episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetails.kt
- ui/episodedetails/src/main/java/app/tivi/episodedetails/EpisodeDetailsViewModel.kt
- ui/followed/src/main/java/app/tivi/home/followed/Followed.kt
- ui/followed/src/main/java/app/tivi/home/followed/FollowedViewModel.kt
- ui/search/src/main/java/app/tivi/home/search/Search.kt
- ui/search/src/main/java/app/tivi/home/search/SearchViewModel.kt
- ui/showdetails/src/main/java/app/tivi/showdetails/details/ShowDetails.kt
- ui/showdetails/src/main/java/app/tivi/showdetails/details/ShowDetailsViewModel.kt
- ui/showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasons.kt
- ui/showseasons/src/main/java/app/tivi/showdetails/seasons/ShowSeasonsViewModel.kt
- ui/watched/src/main/java/app/tivi/home/watched/Watched.kt
- ui/watched/src/main/java/app/tivi/home/watched/WatchedViewModel.kt
As we're handling all config changes in Tivi, there's no need to keep the state flow alive for configuration changes (as described in this [blog post](https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb)).
We can simplify this, and remove the now unnecessary `collectAsStateWithLifecycle()` too.
> Simplify ViewModel state subscriptions

- .github/workflows/baseline-profile.yml
This PR automates baseline profile generation, by running our Macrobenchmark tests on an Android emulator, and then committing the updated baseline profile back to the repository.
If you'd like to know more about baseline profiles, I recommend looking through the [documentation](https://developer.android.com/topic/performance/baselineprofiles/overview).
This workflow does not try to avoid commit cycles, whereby the workflow commits a new baseline profile, which then triggers the action to run again, which commits a new profile... repeat. Instead, it is designed to run on a schedule where it doesn't really matter if another load of workflows are triggered. Currently, it is set to run nightly.
It uses the more commonly used [reactivecircus/android-emulator-runner](https://github.com/Reactive …
> Automate baseline profile generation

- .github/workflows/baseline-profile.yml
It was enabled just for testing purposes. We now rely on the nightly schedule.
> Stop generating the baseline profile on commit

- app/src/main/java/app/tivi/AppNavigation.kt
- common/ui/compose/src/main/java/app/tivi/common/compose/ui/AndroidDialog.kt
- ui/account/src/main/java/app/tivi/account/AccountUi.kt
Due to https://issuetracker.google.com/issues/221643630, the standard dialogs do not support content which changes height. As a workaround, we can turn off platform width support, but that then means that there is no sensible default dialog size.
This PR includes `Modifier.androidMinWidthDialogSize` which implements some sensible defaults based on platform values.
> Fix dialog widths (Account UI)

- .github/workflows/baseline-profile.yml
- benchmark/build.gradle.kts
Adds a setup tweak so that the workflow does not save the Gradle cache after. The previous times I've used this, it was blowing out the GA cache limit, which then pushes out the cache used for my normal CI/CD runs.
Easily fixed by making the workflow only read the cache.
> Re-add API 31 Gradle Managed Device to :benchmark

- benchmark/src/main/java/app/tivi/benchmark/BaselineProfileGenerator.kt
- gradle/libs.versions.toml
Hopefully we'll now see more consistent baseline profiles across runs 🎉. Local testing points to the baseline profiles containing much more profiled content (~15k lines to 27k lines).
> Migrate to collectStableBaselineProfile()

- common/ui/compose/build.gradle.kts
- data/db-room/build.gradle.kts
- data/db-room/src/main/java/app/tivi/data/daos/RoomFollowedShowsDao.kt
- data/db-room/src/main/java/app/tivi/data/daos/RoomLibraryShowsDao.kt
- data/db-room/src/main/java/app/tivi/data/daos/RoomPopularDao.kt
- data/db-room/src/main/java/app/tivi/data/daos/RoomRecommendedDao.kt
- data/db-room/src/main/java/app/tivi/data/daos/RoomTrendingDao.kt
- data/db/build.gradle.kts
- data/db/src/main/java/app/tivi/data/daos/FollowedShowsDao.kt
- data/db/src/main/java/app/tivi/data/daos/LibraryShowsDao.kt
- data/db/src/main/java/app/tivi/data/daos/PopularDao.kt
- data/db/src/main/java/app/tivi/data/daos/RecommendedDao.kt
- data/db/src/main/java/app/tivi/data/daos/TrendingDao.kt
- data/test/build.gradle.kts
- domain/build.gradle.kts
- domain/src/main/java/app/tivi/domain/Interactor.kt
- domain/src/main/java/app/tivi/domain/PaginatedEntryRemoteMediator.kt
- domain/src/main/java/app/tivi/domain/RefreshOnlyRemoteMediator.kt
- domain/src/main/java/app/tivi/domain/observers/ObservePagedLibraryShows.kt
- domain/src/main/java/app/tivi/domain/observers/ObservePagedPopularShows.kt
- domain/src/main/java/app/tivi/domain/observers/ObservePagedRecommendedShows.kt
- domain/src/main/java/app/tivi/domain/observers/ObservePagedTrendingShows.kt
- domain/src/main/java/app/tivi/domain/observers/ObservePagedUpNextShows.kt
- gradle/libs.versions.toml
- ui/popular/build.gradle.kts
- ui/recommended/build.gradle.kts
- ui/trending/build.gradle.kts
This is with the future goal of migrating most of the data layer to use KMP. Had to migrate back to kapt for room-compiler due to issues with KSP
https://github.com/cashapp/multiplatform-paging
Fixes #1090
> Migrate to app.cash.paging:paging

- .github/workflows/build.yml
There's no need to run the separate tasks. Just use ./gradlew build and let Gradle work out the specifics.
> Simplify the build action

- app/src/main/java/app/tivi/AppNavigation.kt
- gradle/libs.versions.toml
- ui/upnext/build.gradle.kts
- ui/upnext/src/main/java/app/tivi/home/upnext/UpNext.kt
Opens the new 'track episode' UI added in #1118, triggering from a swipe quick action from the 'Up Next' list. Uses @saket's Swipe library: https://github.com/saket/swipe
https://user-images.githubusercontent.com/227486/219864700-f1c171dc-7768-47de-953d-3603061fd368.mp4
> Add 'track episode' quick action from 'Up Next'

- app/build.gradle.kts
- common/ui/compose/build.gradle.kts
- common/ui/compose/lint-baseline.xml
- common/ui/compose/src/main/java/app/tivi/common/compose/ui/IconButtonScrim.kt
- gradle/libs.versions.toml
- ui/account/build.gradle.kts
- ui/discover/build.gradle.kts
- ui/episode/details/build.gradle.kts
- ui/episode/track/build.gradle.kts
- ui/library/build.gradle.kts
- ui/popular/build.gradle.kts
- ui/recommended/build.gradle.kts
- ui/search/build.gradle.kts
- ui/show/details/build.gradle.kts
- ui/show/seasons/build.gradle.kts
- ui/trending/build.gradle.kts
https://github.com/slackhq/compose-lints
> Integrate Compose Lint Checks 

- common/ui/compose/src/main/java/app/tivi/common/compose/EntryGrid.kt
- common/ui/compose/src/main/java/app/tivi/common/compose/LazyPagingExtensions.kt
- ui/library/src/main/java/app/tivi/home/library/Library.kt
- ui/upnext/src/main/java/app/tivi/home/upnext/UpNext.kt
Contains a workaround for  https://issuetracker.google.com/issues/177245496.
Due to the way which paging loads data, it will always result in an initial empty state, and then the loaded items. That conflicts with the way which rememberLazyListState() and friends store their state, as they rely on the items being present at the time of (Android) state restoration. To workaround this, we use a different LazyListState while the lazy paging items are empty, and then switcheroo to the standard state once we know we have the items available.
> Fix list position restoration

- data/traktauth/src/androidMain/kotlin/app/tivi/data/traktauth/store/BlockStoreAuthStore.kt
- Re-merge change to migrate from deprecated APIs
- Add stricter API availability checks to avoid crashes on devices with older versions of Play Services
> Fixes around Play Services Block Store

- core/base/src/commonMain/kotlin/app/tivi/animations/Lerp.kt
The Kotlin file `Lerp` under the `:core:base` module had a wrong package name declaration.
There were no usages of the method declared here, so there wasn't necessary any other refactoring.
> Fix package name declaration

- gradle.properties
Can't use it due to an incompatability with Kotlin 1.8 and Gradle 8.1
> Disable Gradle configuration caching for now

- app/proguard-rules.pro
These rule are bundled in Okhttp 4.11.0 for now.
> Remove extra ProGuard rules for Okhttp

- gradle/libs.versions.toml
Much like the trick with the Compose Compiler we can do the same with ktlint to allow Renovate to update.
> Add ktlint to libs.versions.toml

- app/src/main/java/app/tivi/AppNavigation.kt
- app/src/main/java/app/tivi/ComposeScreens.kt
Rather than passing a `ComposeScreens` around in the `AppNavigation`, we pass the necessary composable to each function.
> Make injected composables more explicit

- build.gradle.kts
- settings.gradle.kts
Usages of `allprojects` is discouraged and the recommended way to share the build logic is by using convention plugins (see #1243). This will be done later (#1247). For now, removing some of the code from the `allprojects` block.
More details
https://docs.gradle.org/current/userguide/dependency_management.html#sub:centralized-repository-declaration
> Declare dependency repositories in dependencyResolutionManagement block

- gradle.properties
In Gradle 8.0 release the configuration cache feature was promoted from incubating to stable, and the properties were renamed accordingly. The original properties continue to be honored and no warnings are produced if they are used, but they will be deprecated and removed in a future release.
More details
https://docs.gradle.org/8.1/userguide/upgrading_version_8.html#configuration_caching_options_renamed
> Use new property name for configuration cache

- data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/daos/SqlDelightTiviShowDao.kt
- data/db-sqldelight/src/commonMain/sqldelight/app/tivi/data/show.sq
- data/db/src/commonMain/kotlin/app/tivi/data/daos/TiviShowDao.kt
- data/episodes/src/commonMain/kotlin/app/tivi/data/episodes/TraktEpisodeDataSourceImpl.kt
- data/episodes/src/commonMain/kotlin/app/tivi/data/episodes/TraktSeasonsEpisodesDataSource.kt
- data/legacy/src/commonMain/kotlin/app/tivi/data/mappers/ShowIdToTraktOrImdbIdMapper.kt
- data/relatedshows/src/commonMain/kotlin/app/tivi/data/traktauth/TraktRelatedShowsDataSourceImpl.kt
Many of the Trakt APIs allow sending a string containing: "Trakt ID, Trakt slug, or IMDB ID"
We don't store slugs (and we'd have a Trakt ID any time we had a slug), but we can use IMDb Ids.
> Use IMDb ID when fetching show info

- data/traktauth/src/androidMain/kotlin/app/tivi/data/traktauth/AndroidLoginToTraktInteractor.kt
- data/traktauth/src/androidMain/kotlin/app/tivi/data/traktauth/AndroidRefreshTraktTokensInteractor.kt
- data/traktauth/src/androidMain/kotlin/app/tivi/data/traktauth/LoginTraktActivityResultContract.kt
- data/traktauth/src/androidMain/kotlin/app/tivi/data/traktauth/TraktAuthComponent.kt
- Lazily fetch dependencies. No point creating it all upfront.
- Manually create refresh token request. createTokenRefreshRequest() requires the AuthState to be pre-populated from an auth response which we don't have.
> Tidy up Android Trakt login code

- domain/src/commonMain/kotlin/app/tivi/domain/interactors/SearchShows.kt
- ui/search/src/main/java/app/tivi/home/search/SearchViewModel.kt
Two issues:
- Search query wasn't being passed to the DAO correctly
- The catch() on the flow in SearchViewModel doesn't catch anything from the collect(). Moved to using onEach instead.
> Fix crash reported from searching

- android-app/app/build.gradle.kts
- android-app/app/src/main/java/app/tivi/inject/AndroidApplicationComponent.kt
- api/tmdb/build.gradle.kts
- api/tmdb/src/commonMain/kotlin/app/tivi/tmdb/TmdbComponent.kt
- api/trakt/build.gradle.kts
- api/trakt/src/commonMain/kotlin/app/tivi/trakt/TraktComponent.kt
- gradle.properties
- gradle/libs.versions.toml
This allows us to move inject build config into respective modules. We use build config for injecting API keys, so we can stop using the AGP functionality in `:android-app` as a proxy.
> Use gmazzo/gradle-buildconfig-plugin

- desktop-app/build.gradle.kts
- gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/Spotless.kt
- shared/build.gradle.kts
- Setting Kotlin target to `"src/**/*.kt"` is correct, but it breaks Spotless for the convention plugins. This part will be fixed soon and target reverted
- Using multiple `targetExclude` is not supported, only the last call has any effect. This also means that calls to exclude `buildDir` didn't really do anything. And since there's no `"bin"` directory, removing both excludes
- There are no Gradle Kotlin scripts under the `src` directories
> Fix Spotless configuration

- .github/workflows/build.yml
- No need to run it multiple times
- This is where we'll also run spotless on the convention plugins, which has to be a separate command because Gradle doesn't propagate the requested tasks to included builds, and we need to pass the project directory when running it `./gradlew -p gradle/build-logic spotlessCheck`
> Extract code style checks into separate job

- android-app/app/src/main/kotlin/app/tivi/home/MainActivity.kt
- desktop-app/src/jvmMain/kotlin/app/tivi/Main.kt
- ui/root/src/commonMain/kotlin/app/tivi/home/TiviContent.kt
- ui/root/src/iosMain/kotlin/app/tivi/home/TiviUiViewController.kt
The common implementation of Circuit's rememberCircuitNavigator doesn't do any back handling. Hoisting the backstack and navigator up to each platform fixes it.
> Fix Android back navigation

- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/SearchTextField.kt
- ui/library/src/commonMain/kotlin/app/tivi/home/library/Library.kt
At the moment there is no way to dismiss the keyboard on iOS once opened from Search.
> Dismiss the keyboard when clearing search field

- common/ui/compose/src/androidMain/kotlin/app/tivi/common/compose/FlingBehavior.android.kt
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/EntryGrid.kt
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/FlingBehavior.kt
- common/ui/compose/src/iosMain/kotlin/app/tivi/common/compose/FlingBehavior.ios.kt
- common/ui/compose/src/jvmMain/kotlin/app/tivi/common/compose/FlingBehavior.desktop.kt
- ui/discover/src/commonMain/kotlin/app/tivi/home/discover/Discover.kt
- ui/library/src/commonMain/kotlin/app/tivi/home/library/Library.kt
- ui/search/src/commonMain/kotlin/app/tivi/home/search/Search.kt
- ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetails.kt
- ui/show/seasons/src/commonMain/kotlin/app/tivi/showdetails/seasons/ShowSeasons.kt
- ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNext.kt
At the moment Compose MP using the same spline decay animation that Android uses, which isn't great.
This PR changes this by using our own fling behavior throughout the app.
This allows us to tweak the decay animation to better match iOS. It isn't perfect, but it's a lot better than default.
> Try and make iOS fling feel more 'native'

- ios-app/Tivi/Tivi/Info.plist
- tasks/build.gradle.kts
- tasks/src/androidMain/kotlin/app/tivi/tasks/AndroidShowTasks.kt
- tasks/src/androidMain/kotlin/app/tivi/tasks/SyncLibraryShows.kt
- tasks/src/commonMain/kotlin/app/tivi/tasks/ShowTasks.kt
- tasks/src/commonMain/kotlin/app/tivi/tasks/ShowTasksInitializer.kt
- tasks/src/iosMain/kotlin/app/tivi/tasks/IosShowTasks.kt
- tasks/src/iosMain/kotlin/app/tivi/tasks/TasksPlatformComponent.kt
- tasks/src/jvmMain/kotlin/app/tivi/tasks/TasksPlatformComponent.kt
This uses `BGTaskScheduler` and `BGProcessingTask` to implement a nightly sync of user data. We probably could have got away with BGAppRefreshTask but the extra functionality of `requiresNetworkConnectivity` makes using BGProcessingTask worth it.
Fixes #1381
> Add iOS implementation of ShowTasks

- .github/workflows/build.yml
- gradle/build-logic/convention/build.gradle.kts
- gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/Spotless.kt
Otherwise running Spotless on the root project will analyze 54 Gradle build files and 474 Kotlin files, which will then be re-analyzed by their modules. This is redundant but it also results in long fingerprinting times. For example, it took 18s on CI to fingerprint task inputs for an UP-TO-DATE `:spotlessKotlin` task (on the root project) https://scans.gradle.com/s/sqjswckwfddis/timeline?details=oajzimjzgvapi&expanded=WyI3Il0&toggled=WyIxNzciXQ&view=by-type
> Reduce the scope of spotless tasks

- common/ui/compose/build.gradle.kts
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/DateTimeDialogs.kt
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/DateTimeTextFields.kt
- common/ui/compose/src/iosMain/kotlin/app/tivi/common/compose/ui/DateTimeDialogs.kt
- common/ui/compose/src/jvmCommon/kotlin/app/tivi/common/compose/ui/DateTimeDialogs.kt
This PR moves the existing date/picker Compose based implementation to `jvmCommon` and used for Android + Desktop.
We add a new implementation for iOS which uses a Modal `UIViewController` with an appropriately configured `UIDatePicker` view, all driven from Compose.
https://github.com/chrisbanes/tivi/assets/227486/88628032-1269-493a-aca0-40547348f03b
> Use native date/time pickers on iOS

- core/base/src/commonMain/kotlin/app/tivi/util/AppCoroutineDispatchers.kt
- data/db-sqldelight/src/iosMain/kotlin/app/tivi/data/SqlDelightDatabasePlatformComponent.kt
- data/legacy/src/commonMain/kotlin/app/tivi/data/util/StoreExtensions.kt
- data/popularshows/src/commonMain/kotlin/app/tivi/data/popularshows/PopularShowsStore.kt
- data/recommendedshows/src/commonMain/kotlin/app/tivi/data/recommendedshows/RecommendedShowsStore.kt
- data/relatedshows/src/commonMain/kotlin/app/tivi/data/relatedshows/RelatedShowsStore.kt
- data/search/src/commonMain/kotlin/app/tivi/data/search/SearchRepository.kt
- data/showimages/src/commonMain/kotlin/app/tivi/data/showimages/ShowImagesStore.kt
- data/shows/src/commonMain/kotlin/app/tivi/data/shows/ShowStore.kt
- data/test/src/commonTest/kotlin/app/tivi/data/TestDatabaseInject.kt
- data/trendingshows/src/commonMain/kotlin/app/tivi/data/trendingshows/TrendingShowsStore.kt
- data/watchedshows/src/commonMain/kotlin/app/tivi/data/watchedshows/WatchedShowsStore.kt
- shared/src/commonMain/kotlin/app/tivi/inject/SharedApplicationComponent.kt
- ui/settings/src/main/kotlin/app/tivi/settings/SettingsActivity.kt
Reads are limited to a dispatcher with a parallelism of 4, which is equal to the newly set maximum connection readers on the SQLite driver.
Writes are limited to a parallelism of 1, since that is what SQLDelight will do under the hood anyway. This seems to fix concurrency issues which result in crashes, such as https://github.com/cashapp/sqldelight/issues/4376.
> Move database operations to specific dispatchers

- ui/root/src/iosMain/kotlin/app/tivi/home/TiviUiViewController.kt
The default value of 3.dp is a bit low imo, so we use the Android default value of 8.dp.
https://github.com/JetBrains/compose-multiplatform/issues/3397
> Increase touch slop on iOS

- ui/episode/details/src/commonMain/kotlin/app/tivi/episodedetails/EpisodeDetails.kt
- ui/root/src/iosMain/kotlin/app/tivi/home/GestureNavDecoration.kt
- Reduce the swipeable area to the start-most `16.dp`
- Add nested scrolling support. This is useful for Show Seasons where the content is a `HorizontalPager`
- Fix `EpisodeDetails` not filling the entire window. This caused weirdness with the swipe gesture.
> Tweaks for iOS Gesture Navigation

- ui/root/src/iosMain/kotlin/app/tivi/home/TiviUiViewController.kt
This was added in #1422 as a workaround, but it has been fixed upstream.
> Remove our custom touch slop

- core/logging/implementation/src/androidMain/kotlin/app/tivi/util/TimberLogger.kt
Caused by a Crashlytics call which is called outside of a try catch.
Fixes #1445
> Fix IllegalStateException when Firebase config isn't available

- common/imageloading/src/androidMain/kotlin/app/tivi/common/imageloading/AndroidImageLoaderFactory.kt
- common/imageloading/src/androidMain/kotlin/app/tivi/common/imageloading/CoilCleanupInitializer.kt
- common/imageloading/src/androidMain/kotlin/app/tivi/common/imageloading/ImageLoadingPlatformComponent.kt
Caused by us using the same disk cache location on Android as the previous Coil implementation. This results in any existing Coil-originated disk cache being incompatible with Compose Image Loader. Fixed by using a different cache folder, and deleting the remaining Coil cache folder (if exists).
Fixes #1465
> Fix images not loading

- core/powercontroller/build.gradle.kts
- core/powercontroller/src/androidMain/kotlin/app/tivi/util/AndroidPowerController.kt
- core/powercontroller/src/androidMain/kotlin/app/tivi/util/PowerControllerComponent.kt
- core/powercontroller/src/commonMain/kotlin/app/tivi/util/PowerController.kt
- core/powercontroller/src/iosMain/kotlin/app/tivi/util/PowerControllerComponent.kt
- core/powercontroller/src/jvmMain/kotlin/app/tivi/util/PowerControllerComponent.kt
Enable preference on iOS and Desktop.
> Tidy up PowerController

- data/models/src/commonMain/kotlin/app/tivi/data/models/ShowImages.kt
- data/popularshows/src/commonMain/kotlin/app/tivi/data/popularshows/PopularShowsStore.kt
- data/recommendedshows/src/commonMain/kotlin/app/tivi/data/recommendedshows/RecommendedShowsStore.kt
- data/relatedshows/src/commonMain/kotlin/app/tivi/data/relatedshows/RelatedShowsStore.kt
- data/showimages/src/commonMain/kotlin/app/tivi/data/showimages/ShowImagesStore.kt
- data/trendingshows/src/commonMain/kotlin/app/tivi/data/trendingshows/TrendingShowsStore.kt
- data/watchedshows/src/commonMain/kotlin/app/tivi/data/watchedshows/WatchedShowsStore.kt
Currently we only validate the timestamp of the last 'valid' response, but we should also look at the currently stored value. If the list is empty then it's safe to assume that we should try again with a short TTL.
> Validate empty results

- ui/discover/src/commonMain/kotlin/app/tivi/home/discover/Discover.kt
- ui/root/src/androidMain/kotlin/app/tivi/home/GestureNavDecoration.kt
- ui/root/src/commonMain/kotlin/app/tivi/home/GestureNavDecoration.kt
- ui/root/src/commonMain/kotlin/app/tivi/home/Home.kt
- ui/root/src/commonMain/kotlin/app/tivi/home/TiviContent.kt
- ui/root/src/iosMain/kotlin/app/tivi/home/GestureNavDecoration.kt
- ui/root/src/jvmMain/kotlin/app/tivi/home/GestureNavDecoration.kt
We need to look at storing state better, but this works for now.
> Make flash when navigating to Discover look a bit better

- data/db-sqldelight/src/commonMain/sqldelight/app/tivi/data/upnext_shows.sq
We always want to show followed shows, and then optionally display shows which have been previously watched.
> Tweak up next shows query

- common/ui/compose/build.gradle.kts
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/EntryGrid.kt
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/Layout.kt
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/ui/AppBar.kt
- gradle/libs.versions.toml
- ui/developer/log/src/commonMain/kotlin/app/tivi/developer/log/DevLog.kt
- ui/developer/settings/src/commonMain/kotlin/app/tivi/settings/developer/DevSettings.kt
- ui/discover/src/commonMain/kotlin/app/tivi/home/discover/Discover.kt
- ui/episode/details/src/commonMain/kotlin/app/tivi/episodedetails/EpisodeDetails.kt
- ui/library/src/commonMain/kotlin/app/tivi/home/library/Library.kt
- ui/licenses/src/commonMain/kotlin/app/tivi/settings/licenses/Licenses.kt
- ui/root/src/commonMain/kotlin/app/tivi/home/Home.kt
- ui/search/src/commonMain/kotlin/app/tivi/home/search/Search.kt
- ui/settings/src/commonMain/kotlin/app/tivi/settings/Settings.kt
- ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetails.kt
- ui/show/seasons/src/commonMain/kotlin/app/tivi/showdetails/seasons/ShowSeasons.kt
- ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNext.kt
No longer needed now that Compose Multiplatform v1.5 added WindowInsets support
> Migrate away from InsetsX

- gradle/libs.versions.toml
- ui/account/build.gradle.kts
- ui/account/src/commonMain/kotlin/app/tivi/account/AccountPresenter.kt
- ui/developer/log/build.gradle.kts
- ui/developer/settings/build.gradle.kts
- ui/developer/settings/src/commonMain/kotlin/app/tivi/settings/developer/DevSettingsPresenter.kt
- ui/discover/build.gradle.kts
- ui/discover/src/commonMain/kotlin/app/tivi/home/discover/DiscoverPresenter.kt
- ui/episode/details/build.gradle.kts
- ui/episode/details/src/commonMain/kotlin/app/tivi/episodedetails/EpisodeDetailsPresenter.kt
- ui/episode/track/build.gradle.kts
- ui/episode/track/src/commonMain/kotlin/app/tivi/episode/track/EpisodeTrackPresenter.kt
- ui/library/build.gradle.kts
- ui/library/src/commonMain/kotlin/app/tivi/home/library/LibraryPresenter.kt
- ui/licenses/build.gradle.kts
- ui/popular/build.gradle.kts
- ui/recommended/build.gradle.kts
- ui/root/build.gradle.kts
- ui/root/src/commonMain/kotlin/app/tivi/home/TiviContent.kt
- ui/search/build.gradle.kts
- ui/settings/build.gradle.kts
- ui/settings/src/commonMain/kotlin/app/tivi/settings/SettingsPresenter.kt
- ui/show/details/build.gradle.kts
- ui/show/details/src/commonMain/kotlin/app/tivi/showdetails/details/ShowDetailsPresenter.kt
- ui/show/seasons/build.gradle.kts
- ui/show/seasons/src/commonMain/kotlin/app/tivi/showdetails/seasons/ShowSeasonsPresenter.kt
- ui/trending/build.gradle.kts
- ui/upnext/build.gradle.kts
- ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNextPresenter.kt
Note: the content changing size and/or wrong scroll position when popping back
https://github.com/chrisbanes/tivi/assets/227486/79df46d2-d428-46ba-8f39-b4ccb93a02a6
The content stays stable whilst popping back
https://github.com/chrisbanes/tivi/assets/227486/22b9e9ce-d8b4-4430-929a-2d1dd312aaac
Still need to work out how (or if) I should get this working with Paging, but that can wait.
> Use Circuit's Retained state for back stack support

- core/logging/implementation/src/androidMain/kotlin/app/tivi/util/TimberLogger.kt
- core/powercontroller/src/androidMain/kotlin/app/tivi/util/AndroidPowerController.kt
Current minSdkVersion is 24, so the relative system version judgment logic is no need any more.
> Remove unnecessary Android system version judgment logic.

- desktop-app/build.gradle.kts
When we run `gradle :desktop-app:runDistributable`, it will show the below error:
```log
> Task :desktop-app:runDistributable
Exception in thread "main" java.lang.NoClassDefFoundError: java/sql/DriverManager
at app.cash.sqldelight.driver.jdbc.sqlite.ThreadedConnectionManager.getConnection(JdbcSqliteDriver.kt:122)
at app.cash.sqldelight.driver.jdbc.sqlite.JdbcSqliteDriver.getConnection(JdbcSqliteDriver.kt)
at app.cash.sqldelight.driver.jdbc.JdbcDriver.connectionAndClose(JdbcDriver.kt:119)
at app.cash.sqldelight.driver.jdbc.JdbcDriver.execute(JdbcDriver.kt:130)
at app.cash.sqldelight.db.SqlDriver$DefaultImpls.execute$default(SqlDriver.kt:63)
at app.tivi.data.dbsqldelight.DatabaseImpl$Schema.create-0iQ1-z0(DatabaseImpl.kt:136)
at app.tivi.data.dbsqldelight.DatabaseImpl$Schema.create(DatabaseI …
```
> Fix desktop app distribution

- android-app/app/src/main/kotlin/app/tivi/home/MainActivity.kt
There's no need to run it from Compose so we just use a normal coroutine launch
> Refactor enableEdgeToEdge out of Compose

- gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/ComposeMultiplatformConventionPlugin.kt
This _should_ lead to some nice performance wins, but it might also lead to some subtle Compose bugs.
https://medium.com/androiddevelopers/jetpack-compose-strong-skipping-mode-explained-cbdb2aa4b900
> Try out strong skipping in Compose

- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/LazyPagingExtensions.kt
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/StableCoroutineScope.kt
- ui/library/src/commonMain/kotlin/app/tivi/home/library/LibraryPresenter.kt
- ui/popular/src/commonMain/kotlin/app/tivi/home/popular/PopularShowsPresenter.kt
- ui/recommended/src/commonMain/kotlin/app/tivi/home/recommended/RecommendedShowsPresenter.kt
- ui/trending/src/commonMain/kotlin/app/tivi/home/trending/TrendingShowsPresenter.kt
- ui/upnext/src/commonMain/kotlin/app/tivi/home/upnext/UpNextPresenter.kt
We now use a `rememberRetainedCoroutineScope` to keep a CoroutineScope running in a retained state. This allows to then keep a retained `cachedIn` paging flow running too.
>  Add retained caching for paging flows

- common/ui/compose/build.gradle.kts
- common/ui/compose/src/commonMain/kotlin/app/tivi/common/compose/HazeScaffold.kt
- ui/root/build.gradle.kts
- ui/root/src/commonMain/kotlin/app/tivi/home/Home.kt
> Make bottom navigation bar float above content

- gradle/build-logic/convention/src/main/kotlin/app/tivi/gradle/ComposeMultiplatformConventionPlugin.kt
Needed for Layout Inspector to be able to see all of the nodes in the component tree:
https://issuetracker.google.com/issues/338842143
> Enable Compose Compiler source info

- README.md
I'd love to see Dagger/Hilt KMP, but since this project no-longer uses them, it should probably be removed from the README.
> Removing Hilt mention from README

- core/notifications/src/androidMain/kotlin/app/tivi/core/notifications/AndroidNotificationManager.kt
- core/notifications/src/androidMain/kotlin/app/tivi/core/notifications/PendingNotificationStore.kt
- core/notifications/src/commonMain/kotlin/app/tivi/core/notifications/NotificationManager.kt
- core/notifications/src/iosMain/kotlin/app/tivi/core/notifications/IosNotificationManager.kt
- core/notifications/src/jvmMain/kotlin/app/tivi/core/notifications/EmptyNotificationManager.kt
- data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/daos/SqlDelightEpisodesDao.kt
- data/db-sqldelight/src/commonMain/sqldelight/app/tivi/data/episodes.sq
- data/db/src/commonMain/kotlin/app/tivi/data/daos/EpisodesDao.kt
- data/episodes/src/commonMain/kotlin/app/tivi/data/episodes/SeasonsEpisodesRepository.kt
- data/models/src/commonMain/kotlin/app/tivi/data/compoundmodels/ShowSeasonEpisode.kt
- data/models/src/commonMain/kotlin/app/tivi/data/models/Notification.kt
- data/test/src/commonTest/kotlin/app/tivi/utils/ObjectGraph.kt
- domain/build.gradle.kts
- domain/src/commonMain/kotlin/app/tivi/domain/interactors/ScheduleEpisodeNotifications.kt
- ios-app/Tivi/Tivi.xcodeproj/project.pbxproj
- ios-app/Tivi/Tivi/Info.plist
- tasks/src/androidMain/kotlin/app/tivi/tasks/AndroidShowTasks.kt
- tasks/src/androidMain/kotlin/app/tivi/tasks/ScheduleEpisodeNotificationsWorker.kt
- tasks/src/androidMain/kotlin/app/tivi/tasks/SyncLibraryShowsWorker.kt
- tasks/src/androidMain/kotlin/app/tivi/tasks/TiviWorkerFactory.kt
- tasks/src/commonMain/kotlin/app/tivi/tasks/ShowTasks.kt
- tasks/src/commonMain/kotlin/app/tivi/tasks/ShowTasksInitializer.kt
- tasks/src/iosMain/kotlin/app/tivi/tasks/IosShowTasks.kt
- tasks/src/jvmMain/kotlin/app/tivi/tasks/TasksPlatformComponent.kt
- ui/developer/notifications/src/commonMain/kotlin/app/tivi/developer/notifications/DevNotificationsPresenter.kt
Still very days and needs testing.
> Hook up episodes airing notifications

- data/db-sqldelight/src/commonMain/kotlin/app/tivi/data/daos/SqlDelightUserDao.kt
- data/traktauth/src/commonMain/kotlin/app/tivi/data/traktauth/TraktAuthRepository.kt
- data/traktusers/src/commonMain/kotlin/app/tivi/data/traktusers/TraktUsersRepository.kt
https://console.firebase.google.com/u/0/project/tivi-android-app/crashlytics/app/android:app.tivi/issues/0da9b4d1a827097922747d3ae09dad3c
> Fix crash from DB having multiple `isMe` users
